### ISSUE TITLE
Привести все уровни в соответствие с требованиями

### ISSUE THREAD

**Issue by krashaen** [fullstack-development/developers-roadmap#100]
Нужно пройти по всем файлам из уровней и проверить на соответствие оформления всех  правил, которые составлены и лежат [тут](https://github.com/fullstack-development/developers-roadmap/blob/master/requirements.md#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2)

**Comment by chmnkh** [comment]
https://github.com/fullstack-development/developers-roadmap/issues/68

**Comment by krashaen** [comment]
> боян
> 
> #68
> 
> пысы: не смотри, что там я на себя заассайнил, я это еще не делал и не сильно собирался делать

афигеть, во я слепой))) сорян ща закрою эту фигну)
