### ISSUE TITLE
Поменять задание с дженериками на 2 джуна

### ISSUE THREAD

**Issue by kinda-neat** [fullstack-development/developers-roadmap#104]
Мне изначально не нравился приведенный пример с filterByPropertyAndValue, самое главное там это and в названии, что есть плохой запах для функции, типа filterByPropertyAndValueAndVsemyChemyZakhocheshAndDverZapili.

Сейчас вспомнил гораздо лучше пример, в котором можно тоже самое сделать и это будет real-life case - функция prop: function prop(obj, key) { /*...*/ } и там можно кучу сразу всего совместить (дженерики, extends, lookup types)

**Comment by in19farkt** [comment]
Согласен, пример немного из пальца высосанный) можно еще просто `filterByPropertyAndValue` переименовать в `filterBy`, а по чему она там фильтрует можно увидеть из сигнатуры функции.

**Comment by krashaen** [comment]
> Сейчас вспомнил гораздо лучше пример, в котором можно тоже самое сделать и это будет real-life case - функция prop: function prop(obj, key) { /_..._/ } и там можно кучу сразу всего совместить (дженерики, extends, lookup types)

Можешь подробнее расписать? Я пока не совсем понял твой пример)

**Comment by in19farkt** [comment]
функция `prop` достает из объекта `obj` значение по ключу `key`

**Comment by krashaen** [comment]
> функция `prop` достает из объекта `obj` значение по ключу `key`

просто это есть в handbook) [тут](https://www.typescriptlang.org/docs/handbook/generics.html#using-type-parameters-in-generic-constraints)

**Comment by in19farkt** [comment]
ну да) возможно тогда стОит другой пример запилить

**Comment by kinda-neat** [comment]
Да впринципе пофиг мне кажется, если чувак сможет рассказать как оно работает и почему, оно все об одном и том же)

**Comment by in19farkt** [comment]
> Да впринципе пофиг мне кажется, если чувак сможет рассказать как оно работает и почему, оно все об одном и том же)

Тоже верно)) Эти задания не за этим написаны

**Comment by kinda-neat** [comment]
> Согласен, пример немного из пальца высосанный) можно еще просто `filterByPropertyAndValue` переименовать в `filterBy`, а по чему она там фильтрует можно увидеть из сигнатуры функции.

Да, точняк, или хотя бы в filterBy переименовать

**Comment by krashaen** [comment]
> Да, точняк, или хотя бы в filterBy переименовать

окей) переименую)
