### ISSUE TITLE
jun2/typescript. Добавить вопросы.

### ISSUE THREAD

**Issue by prodderman** [fullstack-development/developers-roadmap#135]
Предлагаю добавить следующие вопросы:
1. Что такое typescript, для чего нужен, какие проблемы решает?
1. Плюсы и минусы типизации
1. Виды/категории типизации (слабая/сильная, статическая/динамическая, явная/неявная, структурная/номинативная) какая типизация у JavaScript/Typescript, можно еще спросить про отличие структурной и номинативной типизации.
1. Mapped types.
1. В дженерики добавить подвопрос про дефолтные значения для типовых переменных.
1. Так же в дженерики добавить вопрос про дженерики для классов (@in19farkt дополни про инферинг, что ты тут хотел)
1. Вопрос про специфичный кейс, при наследовании от Error, если в настройках typescript target: "es5", то instanceof на наследнике не работает. @in19farkt 
1. Вопрос про новую фичу [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions)
1. В вопросе про union и intersection убрать пример с пересечением и объединением типов функций, мне кажется это сложноватая тема для второго джуна

**Comment by chmnkh** [comment]
+, кроме

3. неужели их нету? на 3 джуне например
5. не понял, подробнее бы
6. сильно специфично, не понимаю, почему это маст хэв

**Comment by prodderman** [comment]
Еще предлагаю добавить вопрос: плюсы и минусы типизации на поверхностном уровне

**Comment by Znack** [comment]
с 6-ым я кстати на практике столкнулся как-то недавно :)

2 кстати хорошая тема, надо действительно это расписать бы. Да и в целом я за, спасибо, что предложил 👍

**Comment by krashaen** [comment]
3 есть на тертьем джуне 
> Для чего предназначены Mapped types? Как создать собственный Mapped type?

8 мне кажется благодаря этому примеру и зашаришь джинерики, поэтому против выпиливания)

**Comment by prodderman** [comment]
> 8 мне кажется благодаря этому примеру и зашаришь джинерики, поэтому против выпиливания)

я ошибся, выпилить пример из вопроса про union и intersection

**Comment by krashaen** [comment]
> я ошибся, выпилить пример из вопроса про union и intersection

если ты про этот 
![image](https://user-images.githubusercontent.com/12808495/71512640-b9dc9500-28c9-11ea-819b-6f760620cfd9.png)
то я тоже за)

**Comment by prodderman** [comment]
> 3 есть на тертьем джуне

Да, но мне кажется это тема уровня второго джуна, предлагаю перенести сюда

**Comment by prodderman** [comment]
> > я ошибся, выпилить пример из вопроса про union и intersection
> 
> если ты про этот
> ![image](https://user-images.githubusercontent.com/12808495/71512640-b9dc9500-28c9-11ea-819b-6f760620cfd9.png)
> то я тоже за)

ага, про этот

**Comment by in19farkt** [comment]
По инферингу. Как выводятся типы дженерик аргументов функции если:

- явно указать тип дженерик аргументов при вызове
- не указывать тип дженерик аргументов и
  - дженерик аргумент используется для типизации аргумента функции
  - дженерик аргумент используется для типизации возвращяемого значения

Сформулировал коряво, но думаю смысл понятен, рассказать по каким правилам выводятся типы дженерик аргументов при вызове функций.

**Comment by in19farkt** [comment]
6. тоже с этим сталкивался и потратил немалое кол-во времени чтобы найти официальный костыль в описании брекинг чейнджесов тайпскрипта в вики оффициального репозитория. Поэтому думаю как минимум про эту штуковину нужно помнить, а чтобы про нее помнили все нужно хотя бы вскользь затронуть это на собесе.

**Comment by in19farkt** [comment]
7. нужно добавить сразу после тайпгардов, тема близкая, т.к. assertion функции влияют на типы после вызова.

**Comment by in19farkt** [comment]
> 5 вопрос. не понял, подробнее бы
@chmnkh это к тому что сейчас там пример на функциях, но дженериками же могут быть классы, и там можно ограничить типы не только функций (методов), но и полей класса. Тут же можно спросить какие есть стандартные дженерик классы, как это можно юзать в реакте компонентах.

**Comment by in19farkt** [comment]
Еще по поводу брендинга и флейворинга возможно стоит как-то вопросы раскрыть или отдельно обсудить всеми кто уже сдал эти темы, чтобы у всех было правильное понимание и в дальнейшем принимали этот вопрос нормально. Были у нас вопросики по этой теме, холиварнули немного :)

**Comment by in19farkt** [comment]
Если никто не против, то @MorganaLF возьмет эту задачу (я узнавал, она тоже не против :) ), разберет новые вопросы и попутно напишет вопросики по этим темам.

**Comment by Znack** [comment]
Про брендинг и флейворинг ещё можно добавить в минусы, что это не прокатит для использования ключей у рекордов, например

**Comment by Znack** [comment]
Ну или найти способ, как можно использовать :)

**Comment by in19farkt** [comment]
@Znack а почему не прокатит? вроде же работает оно, вот я [пример](https://www.typescriptlang.org/play/index.html?ssl=19&ssc=20&pln=19&pc=22#code/JYOwLgpgTgZghgYwgAgGIBs4DcD2VQDmAPBtngCoB8yA3gLABQyyA+mAJ4AOEA-AFxpMuKOQDcjAL6NGEAB6c8YZB26CyUIuQA0a4VWQBeZOWQAyXXkIkhFSuIYz5i5VxQBVAM7QAkgBFDFhoeYPggBDoA5J7QEXbSDHIKUEoq7l5QAfRMyCBwALYQAsGhBPZSDgwIOCDByMAAJgLRUH4BEQCMEfaMVTVKAK7pHgIAShBVUPVEzX46zdRGWcwA2g0AugI0EshwHsjNWpLdldW1g9DtAZxQOJwAFA0651AeAJT2vWfpAExXN-cRACOAHcIBEnkN3sgAPTQ5CAIRBAMIg8OQgH4QQACIIA+EFRiMAgiCALhBAAwggFYQeE6VGY+GYwA8IIjkIBxECprFSyEATCCBQjIbGAMRBABwgmMAvCCEwDcIIAZEAFgGkQQCcIDpcchAIwg6OJAsALCC8gWAZhAaQjCfjMcTkAKDRjMUShaT4jB+iAEGBgNVkNdbkQANLIOSQED1PYAawg7BwMB2IHYOiodz97AELp0OAARgArUbjPBTGPGSivAQmJbIKAQMD9KAgZDxhPLSNrMqMIA) писал как можно читать из такого рекорда

**Comment by Znack** [comment]
Ну пропускает, но с костылями, надо `prop` писать :( Плюс flavoring в итоге вообще всё, что угодно позволяет пропускать

**Comment by in19farkt** [comment]
ну тогда нужно ждать когда [номинативные типы](https://github.com/Microsoft/TypeScript/issues/202) введут (или номинальные, хз как правильно)

**Comment by Znack** [comment]
Ну почему, просто пока понимать плюсы и минусы :) В принципе жить можно, просто немного больнее, чем хотелось бы

**Comment by MorganaLF** [comment]
> Про брендинг и флейворинг ещё можно добавить в минусы, что это не прокатит для использования ключей у рекордов, например

@Znack не совсем поняла, нужно добавить вопрос "Какие есть плюсы и минусы у брендинга и флейворинга" или что-то еще?)

**Comment by Znack** [comment]
Ну я не могу однозначно сказать, какую бы формулировку выбрать, но да — про плюсы и минусы лучше явно затронуть, потому что учить эти термины просто ради того, чтобы знать не очень хорошая идея :) надо чтобы было точное представление, когда надо и когда не надо это использовать

**Comment by Znack** [comment]
Желательно уже в вопросах причем расписать все возможные минусы, просто чтобы сдающий объяснил каждый из них и под конец суммировал, где не надо использовать флейворинг, где не надо брендинг и где ничего из этого :)
