### ISSUE TITLE
Выписать список фичей TS не освещенных в handbook

### ISSUE THREAD

**Issue by in19farkt** [fullstack-development/developers-roadmap#14]
Не все фичи описаны в разделе `handbook`, многое можно найти только в разделе `what's new`.

**Comment by Znack** [comment]
Я многие фичи описал в https://github.com/fullstack-development/developers-roadmap/pull/77, пока тогда закрываем? :) Хотя я по релиз логам не проходил, может упустил чего-нибудь. Предлагаю тут еще @kinda-neat подключиться, он сейчас в TS начал активно закапываться :)

**Comment by Znack** [comment]
@in19farkt @kinda-neat можете плиз прочекать насколько полно сейчас TS вопросы на мидла и джуна 3 покрывают тонкости языка? :)

**Comment by in19farkt** [comment]
а у нас же еще один ПР висит не мержнутый по тайпскрипту

**Comment by in19farkt** [comment]
Можно добавить вопросы по конфигурированию тайпскрипта, пробежаться по параметрам тсконфига, там тоже много всего интересного)

**Comment by Znack** [comment]
Ну вроде более-менее решили тему с TS, пока можно закрывать

**Comment by kinda-neat** [comment]
в roadmap круто коротко описаны введенные фичи/изменения
https://github.com/microsoft/TypeScript/wiki/Roadmap
