### ISSUE TITLE
Requirements: добавлять ссылку на то, как выглядят изменения

### ISSUE THREAD

**Issue by kinda-neat** [fullstack-development/developers-roadmap#141]
Добавить требование, чтобы в ПРе была ссылка на то как обновленная версия выглядит, потому что часто нужно оценить насколько органично выглядят изменения, косяки в оформлении чекнуть

**Comment by chmnkh** [comment]
сделаю на этой неделе

**Comment by Znack** [comment]
Не совсем понял, у тебя же дифф как раз между новой и старой версией. Или на что ты тут предлагаешь ссылку делать? Ты про ссылку на старые уровни в риззоме?

**Comment by in19farkt** [comment]
интересно как это будет выглядеть, если изменения затронут не один, а например пять файлов :)

**Comment by in19farkt** [comment]
а вообще можно делать так, если кто не в курсе :)
![image](https://user-images.githubusercontent.com/12945918/72055818-8a238900-32dc-11ea-9765-6ba30eda102b.png)

**Comment by kinda-neat** [comment]
учитывая магию которую показал Диман, у меня больше нет здесь вопросов)0)), разве что требовать чтобы после изменений чекали что визуально ничего не поехало

**Comment by kinda-neat** [comment]
> Не совсем понял, у тебя же дифф как раз между новой и старой версией. Или на что ты тут предлагаешь ссылку делать? Ты про ссылку на старые уровни в риззоме?

ну вот я постоянно прошу
https://github.com/fullstack-development/developers-roadmap/pull/140#issuecomment-572440987
