### ISSUE TITLE
Подробно раскрыть пункты в чуть более сложных вещах в верстке

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#16]
На первого джуна есть вопросы в  CSS, которые сформулированы просто перечислением свойств. Лучше сделать чёткие вопросы и подчеркнуть там нюансы, на которые мы обращаем внимание

**Comment by chmnkh** [comment]
А что там непонятного? Я сейчас прочитал вопросы, и мне кажется что все прозрачно довольно. Да и я вообще не помню, чтобы в цссе на младшего мидла какие-то проблемы с этим были особо) Точно помню с контекстом наложения неочевидно было, но я это написал, а в целом там вроде все ок.

**Comment by chmnkh** [comment]
Мне вообще кажется прямо адски конкретизировать надо только тогда, когда тема какая-то обширная и можно "загулять". А если вопрос про какой-нибудь паддинг или флоат, то там особо не заблудишься при изучении, и упарываться по конкретизации смысла нету, имхо.

**Comment by Znack** [comment]
Не, я про свойства типа теней. Там сейчас реально можно и упороться, мы про это говорили на митапе — такие вещи лучше четкими вопросами формулировать, чтобы и опрашивающие знали, что конкертно спрашивать, и при подготовке понятно было, насколько глубоко копать :)

**Comment by chmnkh** [comment]
Ну я помню про что на митапе говорили и помню проблему. Я ее просто конкретно в этом списке вопросов не вижу, в том числе в тенях: там не супер-много материала, чтобы прочитать его весь, и спросить тоже, имхо)

**Comment by Znack** [comment]
Давай созовём собрание :)
@krashaen  @kinda-neat @in19farkt

**Comment by chmnkh** [comment]
Лучше смотреть это в ветке, которая щас мержится в мастер со вторым джуном, я там правил немного

**Comment by Znack** [comment]
Цитата тех вопросов сейчас:

* Чуть более сложные вещи в верстке:
    * Рамки
    * Тени (в том числе множественные тени для одного элемента)
    * Фоны: `background-(image / position / size / repeat / origin / clip / attachment / color)` и чем отличаются `cover` и `contain`?
    * Градиенты
    * Анимации
    * Трансформации

Я предлагаю все подробно расписать, чтобы по каждому такому пункты были четкие вопросы, по некоторым пунктам, уверен, будет по несколько вопросов

**Comment by krashaen** [comment]
> Цитата тех вопросов сейчас:
> 
> * Чуть более сложные вещи в верстке:
>   
>   * Рамки
>   * Тени (в том числе множественные тени для одного элемента)
>   * Фоны: `background-(image / position / size / repeat / origin / clip / attachment / color)` и чем отличаются `cover` и `contain`?
>   * Градиенты
>   * Анимации
>   * Трансформации
> 
> Я предлагаю все подробно расписать, чтобы по каждому такому пункты были четкие вопросы, по некоторым пунктам, уверен, будет по несколько вопросов

В целом может и согласен, не вижу особо смысла расписывать, но раз надо то фоны на мой взгляд и так достаточно подробно расписаны)

**Comment by Znack** [comment]
А почему нет смысла расписывать? Это же как раз про что говорили на митапе — каждый по своему спрашивает, каждый на разную глубину закапывается, и при подготовке, и при проверке. Поэтому я думаю, надо сделать единообразно как везде — четкие вопросы, четкие ресурсы по теме. Возможно, некоторые нюансы свойств перенести на третьего джуна

**Comment by Znack** [comment]
@GoodDayTodayOkey Ещё кстати тебя не мог меншануть, сейчас могу :)

**Comment by chmnkh** [comment]
Ну чуть лучше на самом деле можно расписать, это ок.
Я сейчас думаю вот над чем: как думаете, стоит явно перечислять свойства в вопросах, типа:
```
    * Рассказать что делают и какие значения могут принимать свойства:
        * `background-image`
        * `background-position`
        * `background-size`
        * `background-repeat`
        * `background-origin`
        * `background-clip`
        * `background-attachment`
        * `background-color`
        * `background`
```
Или вопросы формулировать без явного указания свойств, типа:
```
* Как задать фон для элемента?
* Как изменить геометрическое положение фона?
* Как изменить способ заполнения фоном элемента (тут коряво, надо лучше сформулировать про контейн и кавер, с примерами по идее)?
* ...
```

**Comment by chmnkh** [comment]
Короче наверное первый вариант оставлю, не вижу смысла долбаться со вторым, мы же не заставляем людей зубрить названия свойств.

**Comment by Znack** [comment]
Ну кстати второй вариант мне больше нравится, но тут на твоё усмотрение, можно и первый :)
