### ISSUE TITLE
mid1: переработать вопросы по типам и структурам данных

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/developers-roadmap#163]
1) Топик проработан плохо: есть куча вопросов, поставленных откровенно криво (конкретнее опишу позже). 
2) Плюс, лично у меня есть ощущение, что вопросы не сильно осознанно составлялись, т.е. не понятно, к примеру, почему именно эти структуры, адт, и так далее, и что мы вообще хотим от этого топика.
3) Надо по идее какие-то нормальные ресурсы найти, потому что на тему структур и адт просто адская неразбериха: в одной и той же статье в одном предложении что-то называют адт, в другом - уже структурой, в итоге новичковый мозг просто плавиться начинает.

**Comment by Znack** [comment]
Согласен, что топик очень поверхностно проработан. Вполне норм будет и структуры другие в вопросы добавить, а не оставлять только те, что выбраны сейчас.

**Comment by Znack** [comment]
Результаты обсуждения:
* Вынести Map, Set, WeakSet, WeakMap и сформулировать вопросы про то, как их использовать (не про внутреннюю реализацию и используемые алгоритмы) на третьего джуна в JS
* Начальные вопросы про Data Type, Abstract Data Type, Data Structure и базовые структуры оставить на первом мидле
* Добавить вопросы про двусвязанный список в первого мидла
* Убрать блок про деревья на второго мидла
* Добавить на следующих мидлах блоки про алгоритмы и структуры: поиски (напр, бинарный) в коллекциях, массив, связанный список, стеки, очереди, хэш таблица, графы (включая алгоритм Дейсктры)

**Comment by Znack** [comment]
@sk1e @in19farkt @Zarwlar @chmnkh @alextsk скиньте плиз ещё рекомендуемые источники

**Comment by alextsk** [comment]
### **Алгоритмы и структуры данных** 

### **Анализ**
_(часть первая - взгляд с высоты, не надо требовать пруфы, в основном определения и пару примеров, чтобы общее понимание сформировалось)_
тип, абстрактный тип и структура данных, алгоритм: определения, различия
ассимптотический анализ: что такое, худший, средний, лучший случаи, время и память, O(n) и o(n), что здесь n
амортизированный анализ, вероятностный анализ ( что, зачем)
общие стратегии: брут форс, Divide & Conquer, динамическое прогр-е
NP-complete\hard задачи, как определить, пример
недетерминированные алгоритмы - что это, зачем могут понадобиться

**алгоритмы**
gcd (_все с этого начинают))_
lcm
karatsuba multiplication - (хорошо взрывает голову, не сложный, интересный пример алгоритмической оптимизации известной задачи)


### **Линейные списки**

_(тут можно побольше наводящих вопросов накидать)_
- стек, очередь, двухсторонняя очередь _(потому что есть двусторонний список)_
- список: односвязный, циклический, двусвязный _(преимущества, tradeoff)_
- массив
сложность операций crud на различных структурах _(отсюда хорошо видно что когда лучше использовать)_

**алгоритмы**

- перестановки на массиве _(permutation лучше гуглится)_
- сортировка: лучшая и худшая в среднем, есть ли разница в сложности на массиве и связных списках
- поиск: линейный, бинарный, отличия на массиве и связных списках
- решето эратосфена _(хороший пример tradeof сложности по времени и памяти)_

**Comment by alextsk** [comment]
выше набросал свое представление на 1-го мидла
курсивом выделены мысли вслух, их конечно надо убрать потом)

источники  -
Karumanchi N. - Data Structures and Algorithms Made Easy
Stephens R. - Essential Algorithms. A Practical Approach to Computer Algorithms 
Robert Sedgewick and Kevin Wayne - Algorithms - у них есть и на С и на яве и вроде даже на питоне, кому что нравится
Cormen - Introduction to Algorithms
Cormen - Algorithms Unlocked - это один Кормен но разные книги! unlocked значительно проще
и Кнут конечно

они не сказать что все простые, я их все и близко не осилил, но где то одна тема лучше разобрана, где то другая, даже у Кнута есть главы которые описаны понятнее чем у других

про сложность Stephens самый простой, у Сormena подробнее, есть тета и омега но все еще сжато, у Karumanchi там куча математики, но если ее пропустить то основы понятно написаны
главное не надо пугаться кучи формул, большинство там можно пропустить при обзорном чтении без ущерба

**Comment by Znack** [comment]
@alextsk выглядит неплохо, спасибо, что написал :)
Предлагаю тогда за основу взять твой вариант, но я бы его немного сжал, мне кажется тут уже дофига тем, я бы убрал общие стратегии (которые брут форс, Divide & Conquer, динамическое прогр-е), NP-complete\hard задачи, недетерминированные алгоритмы, массивы. 

И по ресурсам будет вообще супер круто, если ты прямо скажешь, в какой книге какие главы смотреть :)

**Comment by Zarwlar** [comment]
> амортизированный анализ, вероятностный анализ ( что, зачем)
> общие стратегии: брут форс, Divide & Conquer, динамическое прогр-е
> NP-complete\hard задачи, как определить, пример
> недетерминированные алгоритмы - что это, зачем могут понадобиться

Ну эти темы разве что на второго и выше можно ставить, и я не особо-то готов составлять для них вопросы, поскольку сам могу оперировать лишь малой частью этого

**Comment by alextsk** [comment]
> Ну эти темы разве что на второго и выше можно ставить, и я не особо-то готов составлять для них вопросы, поскольку сам могу оперировать лишь малой частью этого

я их хочу на первого потому что я планировал именно на эти темы ~3-5 часов ненапряжного чтения, т.е. очень поверхностно рассмотреть, чтоб знать что такое вообще бывает, обзор области. как анализ стоимости продукта в макконнелле, никто от него менеджером не стал) 
на уровне математики я с этим тоже не умею работать, но не вредно уметь опознать если тебе попадется travelling salesman. 
а стратегии это база для классификации алгоритмов, удобнее их потом сортировать в голове
и возвращаться к ним на верхних уровнях уже не планируется.

> И по ресурсам будет вообще супер круто, если ты прямо скажешь, в какой книге какие главы смотреть

тут как раз зависит от степени погружения, практически все эти темы есть во всех книгах, я лично читаю одно и если становится непонятно читаю то же самое в другой, иногда помогает)
все эти темы обычно в начале, я дальше просто сам не ушел

**Comment by Znack** [comment]
> я их хочу на первого потому что я планировал именно на эти темы ~3-5 часов ненапряжного чтения
> и возвращаться к ним на верхних уровнях уже не планируется.

Ну просто все равно в сумме это 3-5 часов, если ты знаешь где читать и насколько глубоко уходить, то есть тонко чувствовать границу :) У нас же по любому будет, что кто-нибудь будет в итоге заморачиваться и начнет слишком углубляться. Тут поэтому в том числе нужны ресурсы, чтобы более-менее было понятно, каких материалов достаточно.

Я предлагаю более концептуальные и более обширные вещи всё-таки повыше вынести, там тоже могут обзорно изучить тему и рассказать :)

**Comment by alextsk** [comment]
ну да, я там немного в кучу все собрал, если те же стратегии и анализ можно считать за концептуальные, то np и nondeterm - это скорее "неплохо бы знать". 
может как то более явно обозначить ожидания, например сколько времени рассчитано на изучение всего раздела? там при желании по любой из тем можно хорошо закопаться

**Comment by Znack** [comment]
Ну нам в идеале, чтобы на первом мидле за 20 часов можно было все вопросы разобрать. То есть если из твоего текущего варианта убрать концептуальные вещи, которые мы выше с Лехой @Zarwlar описали, но оставить-таки массивы, то примерно вроде так и получается по объему

**Comment by Zarwlar** [comment]
> Надо по идее какие-то нормальные ресурсы найти, потому что на тему структур и адт просто адская неразбериха: в одной и той же статье в одном предложении что-то называют адт, в другом - уже структурой, в итоге новичковый мозг просто плавиться начинает.

Есть кому что по этому пункту предложить?

**Comment by alextsk** [comment]
> Есть кому что по этому пункту предложить?

http://web.cs.iastate.edu/~hridesh/teaching/362/07/01/papers/p50-liskov.pdf

**Comment by chmnkh** [comment]
> > Есть кому что по этому пункту предложить?
> 
> http://web.cs.iastate.edu/~hridesh/teaching/362/07/01/papers/p50-liskov.pdf

каким образом это поможет, конкретно?)

я это читал, не сказал бы что как-то помогло лично мне, хотя и первоисточник

**Comment by chmnkh** [comment]
опишу проблему более подробно

Есть 2 понятия: структуры данных и абстрактные типы данных. По идее, это разные понятия. Т.е. взяв какую-то вещь, например, деревья, должно быть возможным четко сказать, что это - адт, или что это - структура. Поскольку как адт так и структура - термины сами по себе достаточно абстрактные, то четко для себя решить, где те критерии, по которым что-то можно или к структуре или к адт отнести - это, как мне кажется, нифига не просто. 

И вот ты такой вроде как с понятиями ознакомился (напомню, они, на мой взгляд, довольно абстрактные), и решил погрузиться в тему глубже, посмотреть конкретные примеры, и ты начинаешь гуглить, к примеру, деревья. И ты натыкаешься на статью, в которой сначала деревья называют адт, потом структурой, потом опять адт, и т.д. Потом натыкаешься на статью, где это всю дорогу называют адт. Потом натыкаешься на ЕЩЕ ОДНУ статью, где это всю дорогу называют структурой...

Так вот было бы неплохо найти источники, где обе эти темы рассматриваются, где четко определено каждое понятие и разница между ними, вот это вот все. Я не знаю, есть ли такое, но то, что "в интернете" на эту тему полное блядство - это факт, как мне кажется. А когда авторы статей не удосужились в теме разобраться, а статья написали, когда в твоих источниках блядство полное, как ты сам должен в этом разбираться - вообще не понятно.

**Comment by alextsk** [comment]
> каким образом это поможет, конкретно?) это по сути пейпер только про АДТ, 

не совсем, это пейпер с _определением_ АДТ, из нее понятно зачем оно вообще было создано
и да, дерево может быть и структурой и адт) 
зависит от того с какой стороны ты на него смотришь, как имплементер или пользователь.
когда есть куча противоречащих источников я смотрю в первоисточник, поэтому и скинул эту бумагу, мне лично она помогла

**Comment by Zarwlar** [comment]
> мне лично она помогла
А чем именно помогла?

**Comment by Znack** [comment]
Сделано вот тут https://github.com/fullstack-development/developers-roadmap/pull/203
