### ISSUE TITLE
Добавить вопросы про rewriting history

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/developers-roadmap#18]
> а вообще раньше мне нравился раздел про "Отмену изменений" и связь с The Three Trees, такой же я б добавил с Rewriting history и какие команды в каком масштабе могут реализовывать этот rewriting

**Comment by kinda-neat** [comment]
https://rizzoma.com/topic/27524b054ef8054b9e9f3da9c8f8f098/0_b_74cf_8uhn2/ вот это сюда же добавь
