### ISSUE TITLE
Сделать гит отдельным разделом в карте развития

### ISSUE THREAD

**Issue by olgaklimenko** [fullstack-development/developers-roadmap#182]
Вопросы по гиту будут теперь общими и для фронтенда и для бэкенда. На фронте гит на junior-2, и на junior-3. Нужно сделать отдельный раздел для гита.

**Comment by olgaklimenko** [comment]
Я считаю, что самые основы гита обязательно нужны на 1м джуне (у нас несколько ребят, когда пришли, не умели рабоать с гитом).

Предлагаю переносить так: 

frontend git jun-2  -> separate git jun-1
frontend git jun-3  -> separate git jun-3

**Comment by kelizarov** [comment]
Можно вместо `separate` назвать `technologies`.

**Comment by olgaklimenko** [comment]
это я просто чтобы обозначить что раздел отдельный) это не название раздела))

Рзадел назовем коротко и ясно: GIT

**Comment by chmnkh** [comment]
гит со 2 джуна можно смело на 1 двигать, имхо, там базовые вещи

по 3 подумать надо: возможно для 2 это рановато, при этом, какие-то куски оттуда сложно выдернуть, там все вопросы сильно лучше воспринимаются в контексте понимания того, как гит реализован (первый вопрос, по сути)

**Comment by olgaklimenko** [comment]
да, я думаю 3го джуна на 3м и оставить. Просто в гите не будет вопросов на 2-го джуна, это ничего страшного

**Comment by chmnkh** [comment]
ну в целом да, не страшно

**Comment by kinda-neat** [comment]
посмотрел вопросы на 3-го джуна и я за то, чтобы git 3-его джуна перенести на второго, там особо ничего сложного нет, но при этом все нужно и полезно

**Comment by kinda-neat** [comment]
можно кстати вообще не выносить никаких "общих разделов", просто в карте бэкенда положить ссылку на раздел во фронтовской

**Comment by olgaklimenko** [comment]
Тогда на фронте можно и не перетаскивать на 1-го джуна вопросы:) Хотелось обозначить, что раздел общий для всех. Но возможно это тоже будет не очень удобно.

**Comment by kinda-neat** [comment]
> Тогда на фронте можно и не перетаскивать на 1-го джуна вопросы:) Хотелось обозначить, что раздел общий для всех. Но возможно это тоже будет не очень удобно.

угу, цель понятна, но в то же время давно пора перенести вопросы на один уровень ниже, мы много об этом говорили и вот ща заодно можно сделать :)

**Comment by Znack** [comment]
На первого джуна гит норм заносить ещё потому что у нас как раз в программе обучения Git How To есть, можно кстати проверить и если что оттуда некоторые темы нам в карту перенести

**Comment by olgaklimenko** [comment]
все сделано давно
