### ISSUE TITLE
Доработать Basic Design Principles

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#183]
В тему https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/middle-1/design.md можно добавить вопросы:

- Явно уточнить, что желательно предварительно изучить ООП на мидл-1
- Српосить явно про горизонтальное и вертикальное Separation of Conserns
- Можно ли достичь вертикального CoS, но без горизонтального?
- Выпилить вопрос про полиморфизм в KISS
- блок Separation of concerns сразу добавить под Cohesion
- Добавить в Separation of concerns вопрос про сходство и различие с SRP и Cohesion
- К Separation of concerns сравнение с Cohesion
- К Separation of concerns какие антипаттерны и как их избегать? (например, https://sourcemaking.com/antipatterns)

**Comment by chmnkh** [comment]
~~* Явно уточнить, что желательно предварительно изучить ООП на мидл-1~~
нужно решать вопрос целиком: https://github.com/fullstack-development/developers-roadmap/issues/154
~~* К Separation of concerns какие антипаттерны и как их избегать? (например, https://sourcemaking.com/antipatterns)~~
вопрос конский, мне пока не по зубам, ишью: https://github.com/fullstack-development/developers-roadmap/issues/192
~~* К Separation of concerns сравнение с Cohesion~~
дубликат

Итого, остается: 
* Српосить явно про горизонтальное и вертикальное Separation of Conserns
* Можно ли достичь вертикального CoS, но без горизонтального?
* Выпилить вопрос про полиморфизм в KISS
* блок Separation of concerns сразу добавить под Cohesion
* Добавить в Separation of concerns вопрос про сходство и различие с SRP и Cohesion
