### ISSUE TITLE
Обсуждение Mid-1/TypeScript

### ISSUE THREAD

**Issue by Zarwlar** [fullstack-development/developers-roadmap#189]
[Линка на топик](https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/middle-1/typescript.md#typescript)
> Почему использование generic переменных в тегах для Discriminated Unions может сделать программу более склонной к багам? Когда это действительно приводит к багам, а когда нет?

Уже второй раз непонятно о чём идёт речь. Здесь нужен пример, или вообще убрать этот вопрос

> Какие типичные проблемы вывода типов есть?

Нужна конкретизация вопроса: речь идёт о ts или в целом о типизации в языках програмирования? Также нужны источники, потому что не понятно, какой информации достаточного для интервьюеров, да и в целом вопрос по сложной теме, хотелось бы иметь какие-то ориентиры

**Comment by Zarwlar** [comment]
@in19farkt @performanceArtist

**Comment by in19farkt** [comment]
> Что такое Companion Object Pattern? Как для его реализации используется Declaration Merging?

Вообще непонятный вопрос
* почему Companion Object здесь называют паттерном? если немного погуглить, то можно понять, что Companion Object - это некая "структура" присущая какому-то конкретному языку, которая помогает в этом языке реализовать паттерн Фабрика и некоторые другие паттерны, и по сути Companion Object является статической частью некоторого класса
* непонятно при чем тут Declaration Merging? Да, в scala это выглядит как Declaration Merging, но в kotlin это выглядит по другому (Companion Object объявляется внутри объявления класса), а в ТС мы вообще не можем объявить Companion Object и Declaration Merging нам тут никак не поможет.

**Comment by in19farkt** [comment]
нашел откуда растут ноги :) Книга "Programming TypeScript. Making Your JavaScript Applications Scale", там довольно часто упоминается этот "паттерн".

Вот только я опять же не понимаю зачем автор выделил это как паттерн и зачем оно нам вообще надо в TS. Вот [пример из книги](https://www.typescriptlang.org/play/index.html?ts=3.5.1#code/C4TwDgpgBAwgrgJwRAdgYxFAvFA3gKCijhQEtgAuKAcgFEBVAJWqgB8aBxAIQAUX3qAKR4BNfjXoBlACLUA3ISgA3AIYAbOBCoo4AWwBGEBAoC++fGojBYiZOkw4CRabQBiAQXoAZACpVqUrIANOZEAGYIAPa6ABSqGlpQOgZGQcRk1jjwSKgYAHQuHt4+AJRU2XYYeIpEyMCIKHjp5GnxmlAmCkRmJkA) как этот паттерн выглядит в ТС (правда автор видимо не пытался скомпилиться с флагом noImplicitAny :) )

[Так](https://www.typescriptlang.org/play/index.html?ts=3.5.1&ssl=9&ssc=31&pln=9&pc=40#code/C4TwDgpgBAqgdgS2FAvFA5AURgJXVAHwwHEAhABXyPQClyBNKjGAZQBF0BuAKG4GMANgEMAziKgBhAK4AnGRDh8QUAN5RuUKGBkIAbkODQ+AezgjgMqX2DGZACg2atUgEYCEfKPoFSIALig4KQBbFwgZABpHTTBXd08pRGAA+CQozQBKVSgAX15NcwMPKDZMADEAQRgAGQAVFKTUZnYuR0LgYoAzGWNgu29fAKDQ8IioRKQm6TkFJQA6Usqa2oyA6flFZRVoqHlgWThAiAB3SVkNpX6hHwgxieAMnk08vO44E7OZzbsAVjGsXDoR68dazEBzbq9X7-bB4YFAA) это выглядит на классах и статических полях/методах. По мне выглядит лучше, да еще и работает так, как задумывал автор :)

**Comment by sk1e** [comment]
> Какие типичные проблемы вывода типов есть?

С такой постановкой вопроса сложно будет понять что нужно ответить

**Comment by Znack** [comment]
> > Почему использование generic переменных в тегах для Discriminated Unions может сделать программу более склонной к багам? Когда это действительно приводит к багам, а когда нет?
>
> Уже второй раз непонятно о чём идёт речь. Здесь нужен пример, или вообще убрать этот вопрос

Здесь про такой кейс, например:
```typescript
type UserTextEvent<TagText> = {type: Tag, value: string, target: HTMLInputElement}
type UserMouseEvent<TagMouse> = {type: Tag, value: [number, number],
target: HTMLElement}
type UserEvent<TagText, TagMouse> = UserTextEvent<TagText> | UserMouseEvent<TagMouse>
```

— здесь никто не гарантирует, что `TagText` и `TagMouse` не имеют пересекающихся значений (хотя может в TS уже и есть какой-нибудь хитрый способ такой констрейнт наложить, но я сомневаюсь). 

В целом вопрос можно выпилить, он не супер необходимый, он больше для того, чтобы заставить читающего промоделировать ситуацию и подумать о возможных последствиях.

**Comment by Znack** [comment]
Про вопросы о выводе типов согласен, что они слишком общо составлены. Есть варианты, как удобней их сформулировать?

Так норм?
> Что такое вывод типов (относительно любого языка)? В каких случаях TS может выводить типы для генериков? В каких случаях TS автоматически выводить переменную типа как `any`?

**Comment by Znack** [comment]
> почему Companion Object здесь называют паттерном?

Да, это по большей части из книги Черного. В целом я думаю, что можно именно такую формулировку убрать и сформировать конкретно вопрос, можем ли мы экспортить в едином неймспейсе и тип, и терм с одинаковым именем (причем может этот вопрос лучше на джунов унести)

**Comment by chmnkh** [comment]
> Здесь про такой кейс, например:
> ...
> — здесь никто не гарантирует, что `TagText` и `TagMouse` не имеют пересекающихся значений (хотя может в TS уже и есть какой-нибудь хитрый способ такой констрейнт наложить, но я сомневаюсь).
> 
> В целом вопрос можно выпилить, он не супер необходимый, он больше для того, чтобы заставить читающего промоделировать ситуацию и подумать о возможных последствиях.

на мой взгляд, это классический пример вопроса, который ты, @Znack, из своей головы взял, и к ответу на который вообще не понять как люди должны приходить

"моделирование читающим ситуации" - это вообще неопределенный процесс, ну нельзя полагаться на то, что разные люди с разным опытом и мышлением к одному и тому же придут

> Что такое вывод типов (относительно любого языка)? В каких случаях TS может выводить типы для генериков? В каких случаях TS автоматически выводить переменную типа как any?

мне кажется тут +- норм, давайте решим по итогу, я за то, чтобы первый упомянутый Лёхой вопрос в утиль пустить, а второй перефразировать версией Сереги.

@in19farkt @Zarwlar @Znack @performanceArtist @sk1e

**Comment by chmnkh** [comment]
Насчет companion object'a: действительно, гуглится не очень. Согласен с:

> В целом я думаю, что можно именно такую формулировку убрать и сформировать конкретно вопрос, можем ли мы экспортить в едином неймспейсе и тип, и терм с одинаковым именем (причем может этот вопрос лучше на джунов унести)

**Comment by Znack** [comment]
> на мой взгляд, это классический пример вопроса, который ты, @Znack, из своей головы взял, и к ответу на который вообще не понять как люди должны приходить

Насколько я помню, это из Бориса Черного, у него там была рекомендация дженерики для тега не юзать и я подумал, что этот вопрос хорошо иллюстрирует саму суть тегирования, поэтому только добавил. То есть тут как раз прикол вопроса был в том, чтобы внезапно объединить уже знакомую тему (дженерики) с новой и спровоцировать изучающего самого простроить связи и из-за этого глубже понять тему. То есть вопрос не для того преднащначен, чтобы "поймать" кого-то на незнании теории, а как повод на подумать :) Но я вижу хейт таких тем, причем я понимаю с чем они связаны, поэтому и не против убрать

**Comment by performanceArtist** [comment]
Не вижу особой глубины в вопросе про дженерики. Когда его читал, было единственное предположение, что речь о том, что теги должны быть уникальны, а дженерики этого не гарантируют. По-моему это очевидно - у нас на втором джуне уже есть tagged типы - у них и ограничений других нет, кроме как уникальности тегов. Я бы убрал.

Про companion тоже лучше убрать или написать чисто про одинаковое именование. 

Новая формулировка вопроса про вывод типов в принципе понятна.

**Comment by chmnkh** [comment]
> Так норм?
> 
> > Что такое вывод типов (относительно любого языка)? В каких случаях TS может выводить типы для генериков? В каких случаях TS автоматически выводить переменную типа как `any`?

не норм
вопросы

> В каких случаях TS может выводить типы для генериков? В каких случаях TS автоматически выводить переменную типа как `any`? 

звучат так, как будто есть какой-то список случаев, в то время как ответ сам по себе абстрактный довольно получается, и создается ощущение, что ты что-то не так отвечаешь

в то время как чтобы "список случаев" назвать, то это тебе надо сидеть и во время работы лог какой-то составлять, иначе как это запомнить - не понятно

**Comment by Znack** [comment]
Вообще согласен. Тут бы в идеале нормальный источник на эту тему найти. Я в своё время около года назад искал, так ничего про вывод дженериков в TS не нашёл :(

**Comment by performanceArtist** [comment]
Кстати еще второй раз всплыло замечание о порядке вопросов про "Compatibility" и вариантность. По-моему было бы логично сначала рассказать про вариантность, а потом уже в этом ключе говорить про совместимость типов функций и более конкретно, зачем это нужно. Я бы поменял местами вопросы.

**Comment by Znack** [comment]
Сделал ПР по мотивам этого ишью :)
