### ISSUE TITLE
middle1/генераторы: не такой уж и великий рефакторинг вопросов

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/developers-roadmap#194]
* Зачем нужны итераторы, если уже есть массивы?
* Для каких задач по работе с коллекциями итераторы подходят лучше, чем массивы?

Оба этих вопроса, во-первых, об одном и том же, насколько я понимаю.

Во-вторых, оба эти вопроса поставлены некорректно, потому что итератор - это интерфейс над коллекцией любого вида, массива/списка в том числе, т.е. эти понятия в разных плоскостях вообще находятся, мне кажется. При этом еще здесь же речь не столько про массивы, сколько про ограничения любых структур, которые не позволяют представить какие-то большие или бесконечные последовательности.

Мне кажется здесь достаточно просто спросить "Когда итераторы бывают полезны?" и этого будет достаточно. 

* Что такое coroutines (сопрограммы)? Какое отношение они имеют к итераторам и/или генераторам?

предлагаю выпилить, не понятно, к чему тут это

**Comment by Zarwlar** [comment]
> Что такое coroutines (сопрограммы)? Какое отношение они имеют к итераторам и/или генераторам?

Я за то чтобы выпилить этот вопрос. Про те два вопроса, что выше, хотелось бы мнение Серёги узнать

**Comment by Znack** [comment]
Ну про coroutines вопрос чисто для того, чтобы изучающий узнал про эту тему и для него это слово больше не было новым. В любом случае, мне кажется, оно довольно часто встречается и хотя бы обзорно знать, что это почти то же, что генераторы, может быть полезно. Хотя в целом это необязхательно, можно и выпилить

**Comment by Znack** [comment]
> При этом еще здесь же речь не столько про массивы, сколько про ограничения любых структур, которые не позволяют представить какие-то большие или бесконечные последовательности.

Ну тут скорее вопрос в том, что раньше в JS были чисто массивы и как-то жили. Так что вопрос по сути про то, насколько необходимо было вводить новый элемент языка. Почему именно про массивы речь — ну потому что в JS это главный способ представлять коллекции, и до недавнего времени практически единственный некостыльный для представления такого рода данных

**Comment by chmnkh** [comment]
> Ну тут скорее вопрос в том, что раньше в JS были чисто массивы и как-то жили. Так что вопрос по сути про то, насколько необходимо было вводить новый элемент языка. Почему именно про массивы речь — ну потому что в JS это главный способ представлять коллекции, и до недавнего времени практически единственный некостыльный для представления такого рода данных

ну я все равно всё еще считаю, что вопрос "Где они могут быть полезны?" должен это покрывать

и он будет корректнее, потому что текущая постановка выглядит так, как будто массивы и итераторы это что-то взаимозаменяемое, но это не так, потому что итератор это вообще не про структуру данных нифига

**Comment by chmnkh** [comment]
@Znack

**Comment by Znack** [comment]
Просто на вопрос "Где они могут быть полезны?" можно ответив, так и не осветив сравнение с массивами. Но с другой стороны это и некритично, главное в целом сказать про бесконечные коллекции и ленивую подачу элементов. Я бы просто тогда в вопросе эти два момент (про бесконечность и ленивость) отдельно как-нибудь выявил

**Comment by chmnkh** [comment]
- async итераторы и генераторы
- уточнить первый вопрос про циклы и итераторы
-
