### ISSUE TITLE
Jun1. Lists. Foldings lists. Examples

### ISSUE THREAD

**Issue by kostochkin** [fullstack-development/developers-roadmap#197]
> Examples of using associative and non-associative operators as a folding function. What are the differences between these use cases?

Не понятно какая именно ассоциативность имеется ввиду? В математическом смысле, или в Хаскельном?
Некоторые операторы в математике не имеют ассоциативности, при это в Хаскеле они ее имеют, чтобы их можно было миксовать с другими с тем же приоритетом и ассоциативностью
Так же в Хаскеле есть неассоциативные операторы с infix, например (<). Нужно именно такие операторы искать для примеров?

**Comment by kelizarov** [comment]
Привет :)

Все верно, вопрос касается только хаскельных понятий ассоциативности. 

Про второй вопрос тоже верно, нужно рассказать какие операторы в языке Haskell не имеют ассоциативность и почему ее нет.

**Comment by kostochkin** [comment]
Спасибо! Но не очень понятно почему вопрос относится к свёрткам.
