### ISSUE TITLE
Добавить вопросы про Connascence

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#199]
https://en.wikipedia.org/wiki/Connascence — метрика (правда очень размытая) измерения связности. Здесь сборник материалов по теме: https://connascence.io/pages/about.html. 

Думаю, может добавить вопросы в Basic Design Principles в контексте сравнения с Coupling и Cohesion, спросить про возможные типы, про градацию по связности этих типов, про Locality и Degree.

**Comment by Znack** [comment]
Тема спорная. Я не уверен, что прямо с этим стоит заморачиваться, сам полуслучайно узнал про термин этот полгода назад. В основном интересная идея в том, что можно как-то градуировать связность и даже про полуформальную метрику подумать, но всё равно это всё расплывчато и непонятно, насколько на практике будет помогать.

Кто что думает?

**Comment by chmnkh** [comment]
я думаю что если мотивация не ясна, то и обсуждать нечего)

почитав википедию, я тоже не сильно понял, к чему это

**Comment by kinda-neat** [comment]
Как мне показалось что это уже какое-то задроство, в которое впасть можно через лет 10 когда ты уже столько систем написал что тебе интересно еще какие-то общие свойства выделить во всем что ты делал/писал/проектировал. лучше потратить время на проработку темы с data structures, imo

**Comment by chmnkh** [comment]
@Znack может тут решим что-то? мне кажется тема довольно мутная, тем более что никто не так и не высказался явно за)

**Comment by Znack** [comment]
ага, давай закроем ишью
