### ISSUE TITLE
Отсутствует связь между вопросом Шрифты и палитрой RGB.

### ISSUE THREAD

**Issue by AkhmadBabaev** [fullstack-development/developers-roadmap#206]
![image](https://user-images.githubusercontent.com/51095975/83408947-27ae5f00-a41c-11ea-9d87-67b08ebc045f.png)
В выделенном вопросе связь между палитрой RGB и шрифтом не видна, предлагаю вынести его в самостоятельный вопрос. [Страница с вопросом](https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/junior-1/css.md).

**Comment by in19farkt** [comment]
Согласен, не понятно как это туда вообще попало и почему за полтора года ни у кого не возникло этого вопроса ))

**Comment by chmnkh** [comment]
1. По идее этот вопрос должен предыдущим покрываться. 
2. Предыдущий вопрос про цвет в целом, а не только про цвет шрифта, тут согласен. 

Я бы вообще здесь пошел дальше, и выпилил бы вопрос про rgba, вопрос над ним, и написал бы какой-то общий вопрос про цвета с перечислением всех вариантов, чтобы во время собеса никто ничего не забыл.

**Comment by Znack** [comment]
Да, согласен с  @chmnkh. @AkhmadBabaev тебе интересно открыть Pull Request с правками?

**Comment by kinda-neat** [comment]
Не понял в чем проблема? Вопрос находится в подразделе Шрифты и перед конкретным вопросом поставлен общий про форматы в которых можно задать цвет шрифта

**Comment by chmnkh** [comment]
> Не понял в чем проблема? Вопрос находится в подразделе Шрифты и перед конкретным вопросом поставлен общий про форматы в которых можно задать цвет шрифта

проблема в том что цвета в css не только для свойства color существуют, а еще и для других свойств, которые к шрифтам вообще никакого отношения не имеют

**Comment by Znack** [comment]
@AkhmadBabaev открыл PR на этот ишью https://github.com/fullstack-development/developers-roadmap/pull/211
