### ISSUE TITLE
Поправить ссылку на ресурс.

### ISSUE THREAD

**Issue by AkhmadBabaev** [fullstack-development/developers-roadmap#207]
![image](https://user-images.githubusercontent.com/51095975/83410025-44e42d00-a41e-11ea-83a5-3e2286524655.png)
Выделенная ссылка не доступна уже как минимум недели 2. [Рабочий аналог](http://g-mops.net/epica_saitama/epica_layout/index_adaptive.html), [страница с вопросом](https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/junior-1/css.md).

**Comment by Znack** [comment]
О, кстати точно, в риззоме я вроде тоже ссылку менял уже, а тут забыл. Сделаешь PR?

**Comment by in19farkt** [comment]
Для таких правок (когда решение очевидно) можно сразу ПР открывать, прямо на гитхабе нажимаешь редактирование, правишь и создаешь коммит+ПР.

**Comment by in19farkt** [comment]
Но это конечно если есть желание)) За иши тоже спасибо
