### ISSUE TITLE
Добавить вопросы по Bootstrap для старшего джуна

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [fullstack-development/developers-roadmap#21]

**Comment by in19farkt** [comment]
А у нас на проектах активно используется bootstrap?

**Comment by in19farkt** [comment]
это же про юи-кит?

**Comment by GoodDayTodayOkey** [comment]
Что из него оставить пока обсуждается. Целиком его не будем затрагивать, пока что сделаю материал)

**Comment by in19farkt** [comment]
А зачем его вообще обсуждать, если мы его не используем? Для меня это выглядит так: мы прогаем на тайпскрипте, но на страшего джуна давайте обсудим си-шарп.

**Comment by in19farkt** [comment]
Если уж мы хотим обсудить альтернативы, то нужно собрать все эти альтернативы и выделить плюсы/минусы, как-то сравнить. Возможно залезть под капот и посмотреть в архитектуру и идеологию этих китов (но это мне кажется уже не джун). А требовать глубокое понимание юи-китов, которые мы не используем, мне кажется бредом.

И почему именно бутстрап? Первая выдача в гугле - список китов https://dev.to/kayis/react-ui-kits-3fm2, там их штук 20 не меньше, у всех овердохрена звезд, и бутстрапа там кстати почему-то нет))

**Comment by GoodDayTodayOkey** [comment]
Вот здесь обсуждалось какие использовать фрэймворки использовать https://github.com/fullstack-development/developers-roadmap/issues/5 Я просто взялся за первый, и bootstrap не ориентирован исключительно на React. В первом приближении это набор стилей с готовыми классами для элементов (не обязательно Реакта) и расположением их при верстке. А так в целом он достаточно популярен.

**Comment by in19farkt** [comment]
Основной мой посыл: зачем забивать головы джунов всякой абстрактной херней, которую они в 90% случаев не смогут применить на практике, находясь на этой позиции.

**Comment by in19farkt** [comment]
@chmnkh @clicktronix @krashaen @kinda-neat @Znack сходняк :)

**Comment by clicktronix** [comment]
Согласен с Диманом, мне кажется это совсем лишним будет. Мы не используем бутстрап. Я вообще до сих пор его не юзал) знаю только как работает и все. Да и мне кажется популярность его как раз таки уменьшается с приходом гридов, флексов. Не вижу смысла тратить на него время

**Comment by krashaen** [comment]
Пока, отложим эти задачи, сделаем реакт и тс а там видно будет) @clicktronix @in19farkt

**Comment by chmnkh** [comment]
че, может закроем эту и #22 ?

**Comment by Znack** [comment]
Да давай пока отложим, потом либо сделаем, либо закроем :)
