### ISSUE TITLE
Дублируется ссылка в ресурсах

### ISSUE THREAD

**Issue by vovnet** [fullstack-development/developers-roadmap#210]
В списке рекомендуемой литературы (Junior-1 html)2 раза ссылка на одну и ту же статью:
- Альтернативы БЭМ
- Способы организации CSS-кода

ведут на https://habr.com/ru/post/256109/

**Comment by Znack** [comment]
Я только в файле про HTML увидел, а где второй раз? Ну и я думаю, это некритично, если статья неплохо под обе темы подходит :)

**Comment by vovnet** [comment]
> Я только в файле про HTML увидел, а где второй раз? Ну и я думаю, это некритично, если статья неплохо под обе темы подходит :)

ну в файле про HTML - там и указана ссылка два раза, под разными именами)

**Comment by Znack** [comment]
Ааа, ну тогда лучше оставить тот вариант, который именно название статьи несёт. Откроешь Pull Request? :)

**Comment by Znack** [comment]
Исправлено в https://github.com/fullstack-development/developers-roadmap/commit/98cba97e38bad7d30a01325d0d36a65828f9c29d

**Comment by Znack** [comment]
@vovnet спасибо!
