### ISSUE TITLE
Junior1 Иммутабельность данных

### ISSUE THREAD

**Issue by Gmihtt** [fullstack-development/developers-roadmap#212]
Добавить вопрос про иммутабельность данных
Как происходит работа с памятью, как происходит определение одного объекта с помощью друго, как после этого значения одного объекта ссылаются на значения другого (вопрос предполагает понимание того, что такое ссылки в памяти)

**Comment by Znack** [comment]
@CrocodileT @olgaklimenko @kelizarov @vladimirbokor @stanislav-az а на какой уровень будем этот вопрос добавлять? тут вообще тема требующая неплохой проработки с кучей вопросов, возможно, которую даже по хорошему надо на несколько уровней побить — что то на джунах, а что то на мидлах раскрывать только :)

**Comment by kelizarov** [comment]
Ну как минимум я думаю первые вопросы можно со второго джуна спрашивать. Имеет смысл оставить 1 джун только самые основные темы для работы на хаскеле. А память это уже чуть продвинутее.

Вообще тут даже интересный момент: ведь хаскель как бы и подразумевает что человек пишущий код на нем не должен задумываться о том как работает память у его программы. Это скорее такая продвинутая тема.

**Comment by CrocodileT** [comment]
Я согласен, что тема не самая простая
Но мне кажется было бы хорошо, чтобы человек который пишет на хаскеле, понимал, что данные, которые определены, больше не меняются, к примеру, списки и словари в других языках очень даже меняются и это один и тот же объект

Я бы добавил это в вопрос в типы, где собственно эта темы и всплыла.

**Comment by stanislav-az** [comment]
Можно спросить на первом джуне о иммутабельности типичных структур данных, да. А потом спрашивать все более продвинутые вещи. Следующий этап, например, там где были вопросы про `MVar`. А дальше уже где-нибудь вопросы про работу с памятью.
