### ISSUE TITLE
Backend/Databases

### ISSUE THREAD

**Issue by vladimirbokor** [fullstack-development/developers-roadmap#214]
Переносим на **Middle-1**:

- [ ] Все темы с **Junior-3**;
- [ ] Следующие вопросы с **Junior-1**:

      - What are integrity and consistency?
      - What is ACID?
      - What is projection?

Удаляем вопрос с **Junior-1**: _What are base operations for relations?_

**Comment by stanislav-az** [comment]
>Удаляем вопрос с Junior-1: What are base operations for relations?

Может лучше его перенести на mid-1?
