### ISSUE TITLE
Добавить вопросы по MATERIAL-UI для старшего джуна

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [fullstack-development/developers-roadmap#22]

**Comment by in19farkt** [comment]
Тут тоже не однозначно. Кит конечно крутой, запаривается над доступностью, и всё такое. Но он использует jss, а мы вроде пришли к тому, что нужно от него отказываться.

Конечно если не использовать динамические стили, то просадки в производительности нет и можно оставить jss только на уровне кастомизации MUI компонент, а в остальном проекте писать scss. Меня в целом такой подход устраивает, как минимум мне кажется, что кастомизация кита через jss - процесс более простой и предсказуемый. Но тут тогда не понятно что делать с темой, одновременно поддерживать тему в jss и в scss - такое себе.

@Znack @kinda-neat @chmnkh @NikitaRzm @clicktronix @krashaen нужны мнения.

**Comment by clicktronix** [comment]
А почему решили добавлять вопросы по китам для старшего джуна? Есть этом большая необходимость? Может лучше добавить вопросы по кастомизации элементов через js.

**Comment by in19farkt** [comment]
Если мы активно используем какой-то юи-кит, то логично изучить его возможности, чтобы не изобретали свои велосипеды. Просто были уже случаи, когда писали свою реализацию, а потом просто заменяли на готовое, хорошо проработанное решение из кита.

**Comment by krashaen** [comment]
> Может лучше добавить вопросы по кастомизации элементов через js.

может быть интересным, можешь [сюды](https://github.com/fullstack-development/developers-roadmap/issues/6) написать идеи?)
@clicktronix

**Comment by clicktronix** [comment]
@in19farkt тогда нам надо самим определиться сначала как будем использовать MUI :) Согласен с этим:

> Меня в целом такой подход устраивает, как минимум мне кажется, что кастомизация кита через jss - процесс более простой и предсказуемый.

@krashaen Я думал кастомизация через js не особо подойдет к продвинутому css :D

**Comment by kinda-neat** [comment]
Мне кажется эта тема абсолютна не нужна, даже не приложу ума зачем это нужно
