### ISSUE TITLE
Вынести часть раздела с алгоритмами и структурами данных из 1-го мидла на 2-го

### ISSUE THREAD

**Issue by sk1e** [fullstack-development/developers-roadmap#234]
Выносить по приниципу сложности: более сложные вещи переносить, более простые оставлять.

Предлагаю следующее разделение, [смотреть тут](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md):

Оставить на первом мидле:

1. [Определение](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md)
2.  [Анализ](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md#%D0%BF%D0%B0%D1%80%D0%B0%D0%B4%D0%B8%D0%B3%D0%BC%D1%8B-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%BE%D0%B2)
3. [Данные](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md#%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5) [Списки, Стэк и очередь, Графы и деревья]
4. [Алгоритмы](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md#%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%8B) [DFS, BFS, Сортировки, Поиск]

Вынести на второго мидла:

1.  [Парадигмы](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md#%D0%BF%D0%B0%D1%80%D0%B0%D0%B4%D0%B8%D0%B3%D0%BC%D1%8B-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%BE%D0%B2)
2. [Данные](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md#%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5) [Хэш таблица]
3. [Алгоритмы](https://github.com/fullstack-development/developers-roadmap/blob/46e37ff616c4270269a1897285c2d4d201cd7d98/frontend/middle-1/algorithmsAndDataStructures.md#%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%8B) [Алгоритм Дейкстры] (тут мало, есть идеи что добавить?)

**Comment by sk1e** [comment]
Предлагаю добавить на 2-го мидла материал по формальным языкам. Иногда появляется интерфейс по вводу формул которые разбираются на фронте и которые целесообразно разбирать специальными алгоритмами

**Comment by Znack** [comment]
Чтобы чуть более равномерно распределить, я бы предложил ещё убрать что-нибудь с первого мидла и перенести на второй. Может, например, Графы и Деревья + Алгоритмы по ним в виде DFS и BFS на второго перенести? А сортировки и бинарный поиск можно и на списках обычных показать, их оставить на первом.

**Comment by alextsk** [comment]
я бы оставил на первом парадигмы и включил в анализ классы сложности (np-hard, complete), там немного и с ними неизбежно сталкиваешься в процессе чтения 
можно включить простые численные алгоритмы, GCD, умножения, чтобы не возникало ощущения что алгоритмы это всегда про структуры
на второго вынести все нелинейные структуры и алгоритмы к ним, т.е. графы, деревья, хэш мап, 
добавить trie, без него как то список не полон

по формальным языкам не понял идею, если это про TLA+ и тд, то как то круто, а если в математическом смысле то js уже формальный язык 
если про синтаксический анализ то это уже компиляторы, я лично не против них, но это уже тянет на отдельную тему вне алгоритмов

**Comment by sk1e** [comment]
> по формальным языкам не понял идею

Про генераторы парсеров типа https://pegjs.org/ и связанную с этим теоретическую базу

**Comment by alextsk** [comment]
> генераторы парсеров

ну да, компиляторы компиляторов. 
мне кажется это слабо связано с тем что сейчас в разделе, скорее развитие темы регулярок.

**Comment by Znack** [comment]
> я бы оставил на первом парадигмы и включил в анализ классы сложности (np-hard, complete), там немного и с ними неизбежно сталкиваешься в процессе чтения
> можно включить простые численные алгоритмы, GCD, умножения, чтобы не возникало ощущения что алгоритмы это всегда про структуры
> на второго вынести все нелинейные структуры и алгоритмы к ним, т.е. графы, деревья, хэш мап, добавить trie, без него как то список не полон

— мне это в целом нравится, кажется что так более сбалансировано получится.

**Comment by Znack** [comment]
> Про генераторы парсеров типа https://pegjs.org/ и связанную с этим теоретическую базу

А тут я предлагаю в отдельную тему тогда оформить, возможно даже на middle-3 или middle-4 :)

**Comment by sk1e** [comment]
> включил в анализ классы сложности (np-hard, complete), там немного и с ними неизбежно сталкиваешься в процессе чтения

Так много же. Классов много, обилие математики в определениях классов, математика включает различные теоремы, машину тьюринга. Я думаю такое лучше отдельным факультативным разделом оформлять

**Comment by sk1e** [comment]
Итак, рабочий вариант на текущий момент:

Оставить на первом мидле:

Определение
Анализ
Парадигмы
Данные [Списки, Стэк и очередь]
Алгоритмы [GCD (Евклида), Сортировки, Поиск]

Вынести на второго мидла:

Данные [Хэш таблица, Графы и деревья]
Алгоритмы [DFS, BFS, Алгоритм Дейкстры]

Классы я не включил (см. коммент выше) Про компиляторы соглашусь. 
Trie мне кажется лучше уже убрать на дальнейших мидлов, и добавить туда ещё пару-тройку структур для деревьев для более полной картины.

Есть у кого-нибудь возражения с таким вариантом?

**Comment by alextsk** [comment]
в целом мне норм

в алгоритмы 1 я бы добавил еще че нить с простыми числами

про np я предлагаю не уходить глубоко. просто понимать их отношение и основные проблемы, почему travelling salesman не решается дийкстрой и где они в этой схеме
![image](https://user-images.githubusercontent.com/16453186/92569898-61a8c000-f2ab-11ea-8c70-ed0b16d6dfc8.png)

trie мне кажется на фоне хеш мапа удобно рассматривать, но я тут не настаиваю

а в теорию вычислимости можно уже на определении алгоритма упасть при желании)

**Comment by Znack** [comment]
> Итак, рабочий вариант на текущий момент:

Да, мне тоже вариант норм

**Comment by performanceArtist** [comment]
Меня последний вариант устраивает.

**Comment by sk1e** [comment]
> про np я предлагаю не уходить глубоко. просто понимать их отношение и основные проблемы, почему travelling salesman не решается дийкстрой и где они в этой схеме
> ![image](https://user-images.githubusercontent.com/16453186/92569898-61a8c000-f2ab-11ea-8c70-ed0b16d6dfc8.png)
> 

Если про это спрашивать, то нужно дать какой-то материал где это объясняется. Я не могу найти такой чтобы объяснялось неглубоко. Мне вообще кажется что нет смысла оперировать терминами не зная и не понимая их полного определения. Там даже в названии класса заложена недетерминированная машина тьюринга. Как это объяснять не объясняя что это за машина? Я считаю что понимание должно быть полным, неполное понимание будет отрицательно сказываться на практическом применении знания.

**Comment by sk1e** [comment]
> в алгоритмы 1 я бы добавил еще че нить с простыми числами

Решето эратосфена? Там просто. Финальным вариантом будет:

Оставить на первом мидле:

Определение
Анализ
Парадигмы
Данные [Списки, Стэк и очередь]
Алгоритмы [GCD (Евклида), Решето Эратосфена, Сортировки, Поиск]

Вынести на второго мидла:

Данные [Хэш таблица, Графы и деревья]
Алгоритмы [DFS, BFS, Алгоритм Дейкстры]

Классы я не включил (см. коммент выше) Про компиляторы соглашусь.
Trie мне кажется лучше уже убрать на дальнейших мидлов, и добавить туда ещё пару-тройку структур для деревьев для более полной картины.

Есть у кого-нибудь возражения с таким вариантом?

**Comment by sk1e** [comment]
Кто что думает по поводу добавления trie на 2-го? Мне кажется можно добавить, её можно для эффективного автокомлита использовать, частая задача для фронте.

**Comment by chmnkh** [comment]
![image](https://user-images.githubusercontent.com/18498637/92728377-d27ad580-f39a-11ea-9d17-31c0f355b621.png)

![image](https://user-images.githubusercontent.com/18498637/92728435-e9b9c300-f39a-11ea-9384-380f20fd1a6f.png)

**Comment by Znack** [comment]
Я предлагаю тут тогда начать финальный вариант реализовывать, а про trie в отдельном ишью обсудить :) Мне не кажется, что это уже столь необходимые знания, хотя они и могут в некоторых случаях, действительно, пригодиться

**Comment by Znack** [comment]
Реализовал в https://github.com/fullstack-development/developers-roadmap/pull/203
