### ISSUE TITLE
Junior-1/Git

### ISSUE THREAD

**Issue by olegromashin** [fullstack-development/developers-roadmap#235]
Предлагаю явно добавить вопросы по определениям, которыми надо будет оперировать по ходу сдачи:

1. Что такое коммит?
2. В виде чего Git хранит коммиты? - Здесь ожидается упоминание того, что Git хранит состояния репозитория снимками, а не через дельту изменений. В принципе не очень согласен, что стоит спрашивать такое на первом джуне, но от меня очень хотели услышать ответ на этот вопрос, поэтому раз мы такое спрашиваем, то стоит явно добавить.
3. Что такое HEAD? - Есть вопросы на третьем джуне, но думаю здесь тоже полезно базовое понятие.

Также думаю надо добавить вопросы, которые заставят интервьюируемого немного попрактиковаться перед сдачей:
1. Как стянуть удалённую ветку, которой нет в локальном репозитории?
2. Как отправить локальную ветку, которой нет в удалённом репозитории?
3. Вы забыли добавить несколько файлов в индекс и сделали коммит, но ещё не отправили изменения в удалнный репозиторий. Как можно добавить забытые файлы в сделанный коммит? Можно ли так делать, если вы забыли добавить файлы в индекс, но уже сделанный коммит в удалённый репозиторий? - Вопрос про флаг --amend. Есть на третьем джуне, но считаю, что надо уметь пользоваться сразу.
4. Как сделать коммит отменяющий изменения сделанные в одном из предыдущих коммитов? - Тоже есть на третьем джуне, но полезно с самого начала.

В идеале, я бы хотел добавить блок вопросов по конфликтам, но возможно этого будет уже слишком много. Я научился с ними работать уже на проекте.
Как вариант, можно написать практическое руководство по работе с конфликтами, которое будем рекомендовать читать в последнюю очередь, когда уже есть понимание всех базовых вещей. И тогда составить блок вопросов по этому руководству.
Та же штука со stash: очень полезно для мультизадачности, но не спрашиваем.

А вот тонкости с видами merge считаю излишни, практической пользы не несёт, лучше спрашивать про stash.

Помимо этого перед сдачей многие советуют один и тот же источник: https://git-scm.com/book/ru/v2
Я готовился по первым трём главам отсюда, как по мне здесь написано более френдли для новичков, чем в указанных сейчас источниках. Особенно для первых джунов.
Я бы оставил только его. Просто добавлять четвёртым уже будет лишним.

**Comment by Znack** [comment]
`stash` у нас есть на третьем джуне :) В целом то, что предлагаешь с третьего джуна перенести, можно, но у нас тогда первый джун очень разбухнет — это приведёт не только к тому, что готовиться дольше будут, но и что интервью будут гораздо дольше проходить :( Я думаю, что если прямо сверх-критичной надобности нет, то лучше там на первом джуне оставить именно самое необходимое. В принципе `stash` и тд могут изучить те, кому на практике это понадобится, а потом дойдя до 3-го джуна системно уже к вопросу подойти :) То есть сам факт, что `stash` на третьем джуне не говорит, что его не надо изучать, пока ты первый джун, это просто говорит что знания опциональны и тут каждый пусть решает сам, чаще всего отталкиваясь от задач на практике :)

Про стянуть и отправить ветку лучше явно уточнить все детали вопроса: например, стягивая ветку есть ли требования сразу переключаться на неё и тд. Может быть лучше даже формулировку явно сделать от тех команд, про которые ты хочешь, чтобы рассказали (checkout или fetch в частности и тд).

Про то, как Git зранит коммиты и что такое HEAD я бы тоже не переносил с третьего джуна, возможно, что тебе лишние вопросы задавали, такие вещи, которые не про базовые практические приемы, а про внутреннее устройство и концепции лучше оставлять на будущие уровни :) Возможно, стоит явно обсудить с теми, кто принимал уровни, может они не знали, что у нас эти темы на третьем джуне есть

**Comment by olegromashin** [comment]
Согласен с логикой по поводу чрезмерного объёма. Что думаешь на счёт замены тонкостей с `merge` на базовое применение `stash`? На своём примере могу сказать, что про флаги `merge` мало что помню, да и не потребовалось ни разу, а вот `stash` пользуюсь периодически. А по объёму про `stash` спрашивать меньше, если не углубляться.

Про вопросы с ветками можно переформулировать так:
1. Как стянуть и сразу переключиться на удалённую ветку, которой нет в локальном репозитории с помощью `fetch` и `checkout`?
2. Как отправить локальную ветку, которой нет в удалённом репозитории с помощью `push`?

**Comment by Znack** [comment]
А про мержинг ты говоришь именно про эти вопросы?

> Что такое fast-forward merge?
> Что делают флаги --squash и --no-ff?


Про ветки вопросы вроде сейчас понятней стали, но тут еще надо поспрашивать тех, кто сами принимали не так давно :) Я посмотрю, кто у нас сдавали эту тему

**Comment by olegromashin** [comment]
> А про мержинг ты говоришь именно про эти вопросы?

Ага, про них.
Про `stash` чтобы те кто будут принимать лишнего не спрашивали можно вопросы под односложные ответы добавить:
1. Можно ли переключиться на другую ветку, если в текущей рабочей директории есть изменения?
2. Как спрятать все изменения текущей ветки? Самый базовый случай. - Чтобы написали `git stash`
3. Как посмотреть список спрятанных изменений в текущей ветке? - Чтобы написали `git stash list`
4. Как вернуть последние спрятанные изменения и удалить запись о них в истории? Самый базовый случай. - Чтобы написали `git stash pop`

**Comment by Znack** [comment]
Ну вот я бы про мержинг эти подвопросы не убирал, всё-таки это важная фича. Может быть разве что второй про флаги перенёс бы на третьего джуна :) Понимать это надо, рано или поздно

Про stash можно подробно расписать, было бы круто, явное лучше неявного :) Правда там вопросы надо так формулировать, чтобы точно понятно было что ты про `stash` говоришь, потому что если просто голую формулировку "как спрятать изменения", то будет не совсем очевидно, что ожидается в ответе :)

**Comment by Znack** [comment]
Eeee, it's done! Thanks @Odeyaloleg!
