### ISSUE TITLE
Подробней расписать вопросы про системы сборки

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#24]
На джуне подробней раскрыть, как работать с лоадерами, как с плагинами (их конфигурация и их композинг). 

на какого-нибудь мидла добавить написание своих лоадеров и своих плагинов, концептуальные вопросы про то, как они работают.

**Comment by GoodDayTodayOkey** [comment]
Добавлю вопросы в раздел системы сборки на третьего джуна. Концептуальные с написанием плагинов на 2-ого мидла.

**Comment by krashaen** [comment]
> Добавлю вопросы в раздел системы сборки на третьего джуна. Концептуальные с написанием плагинов на 2-ого мидла.

Мне кажется вторую часть логичнее написать чуваку, который уже на уровне второго мидла) а то как то странненько получается)

**Comment by chmnkh** [comment]
+, темы для миддлов должны минимум миддлы делать

Валентин, только не воспринимай на свой счет, если бы любой другой джун полез миддловские темы добавлять, я бы то же самое написал.

**Comment by chmnkh** [comment]
> На джуне подробней раскрыть, как работать с лоадерами, как с плагинами (их конфигурация и их композинг).

зачем это надо? сильно частная задача

> на какого-нибудь мидла добавить написание своих лоадеров и своих плагинов, концептуальные вопросы про то, как они работают.

зачем это надо? сильно частная задача

**Comment by in19farkt** [comment]
Плюсую @chmnkh.

Мне кажется, что не нужно всех заставлять глубоко понимать лоадеры и плагины вебпака и тем более писать свои. Достаточно хорошо разобрать какие задачи с их помощью можно решать, и тогда 1% столкнувшихся с какой-то специфичной задачей будут иметь ввиду, что эту задачу можно попробовать решить с помощью написания своего лоадера/плагина.

**Comment by NikitaRzm** [comment]
Это точно лишнее, я также считаю. Важно понимать системы сборки, общий лэйаут АПИ и архитектурно разве что, но как писать плагины и лоадеры - я не уверен, что это должно быть прям в карте развития. По поводу специфичности в подтверждение кину - что вон у Паши только появилась таска на суперлегаси написать простенький лоадер. Там комьюнити широкое и все уже написано скорее всего.

Если нужно что-то затвикать или сделать специфичную задачу - можно написать плагин или лоадер, но там во первых нюансов куча, во вторых пишется постоянно по разному, т.к. там вариантов написания и hijaking масса в силу архитектурных особенностей вебпака - сложно структурировать без конкретного кейса знания по тому, как писать плагины и лоадеры. Вкупе с сомнением что это не мастхэв в карте развития - я бы сказал, что не надо включать и раздувать да.

**Comment by GoodDayTodayOkey** [comment]
Окей, да, согласен. Снимаю с себя таску.
