### ISSUE TITLE
Книги "Ремесло программирования" и "Совершенный код"

### ISSUE THREAD

**Issue by olegromashin** [fullstack-development/developers-roadmap#242]
Сейчас в карте присутствует две книги. Обе хоть и хорошо написаны, но во многом повторяют друг друга. Время тратится на перчитывание уже освоенного материала.
Предлагаю оставить только одну из книг или убрать дублирующие главы.

В ремесле я косо смотрю на 16 главу. Полезной информации не несёт, просто настраивает на то, что в команде могут встречаться разные типы людей. Не сказал бы, что это помогло мне психологически.

В совершенном коде прочитал только первые 6 глав и предлагаю убрать все 6.
Первая часть(главы 1-4): уже написано в ремесле и, как мне кажется, намного лучше.
Главы 5-6: принципы ООП и проектирование архитектуры на классах. У нас не используются ООП и классы, а в книге такого понятия не вводится. Я думаю тем, кто не имел опыта, это очень сложно читать, ещё и на незнакомом языке(C++).

Кто-то хотел отметить главу про именование у МакКоннелла как мастхэв: просто напомню, что у Гудлиффа тоже хорошо и подробно написано. 

Далее субъективно: МакКоннелла читать не понравилось вообще. Если он весь так написан, то я бы его убрал полностью. Вещи там полезные, но во первых: важное уже было прочитано в ремесле, во вторых: много нерелевантного, в третьих: как мне кажется, на втором джуне у нас в принципе не может быть разработчиков такого уровня, которые могли бы не понимать всех важных принципов, которые рассматриваются в книге.  Почему так категорично: главы достаточно большие, а из нового  я для себя вынес только то, что объявление приватных переменных-членов и методов класса в C++ можно спрятать с помощью указателя.

Хотелось бы узнать мнения других по каждой из книг: какие главы обязательны, а какие не нужны. Особенно те, кто читал обе книги, напишите, плиз, что вы думаете.

**Comment by kelizarov** [comment]
>  У нас не используются ООП и классы, а в книге такого понятия не вводится.

Ну такой аргумент довольно слабый мне кажется, чтобы выпиливать тему. Тема ООП достаточно большая и широко используемая, и даже если мы ее активно не практикуем, не значит что мы должны обходить ее стороной. В книге достаточно хорошо описан сам принцип, при этом глубоко не уходит в объяснении самого подходу. Плюс как по мне это неплохая практика попытаться провести параллели с ФП, например как можно такие же подходы и методики попробовать на ФП'шном языке.

**Comment by stanislav-az** [comment]
Начнем с того, что когда я сдавал Макконнелла хотел его полностью убрать из карты тоже :D Я спорил с @Znack что это все не нужно на карте развития для ФПшника. Но уже после сдачи у меня прошло отвращение к ООП, и только некоторые разделы книги в итоге были записаны в бесполезные.
Ремесло программиста я не читал, содержание не смотрел, но если там обсуждаются точно такие же вещи как у Макконнелла, то может быть стоит оставить одну книгу. Вот самые интересные моменты из Макконелла, если их нет в ремесле, на мой взгляд, нельзя убирать его:

- Accidential and essential complexity 
- Инкапсуляция, абстракция, сокрытие информации 
-  Сопряжение и Связность
- Ошибки: устойчивость, или корректность 
- Закон Парето 80/20 
- Итеративный и последовательный процесс проектирования 
- Восходящее / нисходящее проектирование 
- Стратификация при проектировании

Думаю хейт ООП не обоснован, тем более что ты его вроде кодил на C++) Когда ты читаешь, нужно абстрагироваться от ООП, и проводить параллели с ФП. Если это сделать, то общие вещи для ООП и ФП выделяются в принципы написания хорошего кода как раз) И вообще, полезно иметь кругозор, как нельзя замыкаться только в ООП, так и только в ФП.

И еще вот разделы, которые я думаю можно убрать:

- 13.2. Указатели 
- 17.3. Оператор goto
- 26.2. Циклы
- 31 Форматирование и стиль

**Comment by olegromashin** [comment]
@kelizarov @stanislav-az 
Я, видимо, не корректно выразил свою точку зрения. Я ничего не имею против ООП, но книга требует знания классов и того как с ними работать. На этом фундаменте описываются концепции ООП и проектирования на классах. Не поминаю как это будет понимать человек, который не работал со всем этим. Никакой вводной главы нет, примеры на незнакомом(скорее всего) языке. Сейчас прочитал седьмую главу и продолжаю недоумевать, как человек будет сдавать часть с макросами, если он не знает, что это?
Ну вот просто представьте человека, у которого знания только нашей карты развития. Он открывает книгу и ему говорят: ну вот классы связывай так, а макросы пиши так, вот тебе примеры на C++.

**Comment by olegromashin** [comment]
Я понимаю, что эти темы хорошо влияют на кругозор и помогают лучше видеть картину, но в книге ООП объясняется с использованием незнакомых нашему разработчику инструментов. Я считаю изучение ООП лучше сделать отдельной темой на мидла с каким-нибудь ОО языком и практическим заданием.
А сейчас без закрепления с непользуемым языком эти знания уйдут.
По поводу того, что касается не ООП: я посмотрю что за темы, про которые написал @stanislav-az , но вот эти есть в ремесле:

>     * Сопряжение и Связность

>     * Итеративный и последовательный процесс проектирования

**Comment by stanislav-az** [comment]
Это книга не ставит целью изучение, или исследование ООП. Но здесь изложены обзорно основные принципы, которые применяются в том числе в ООП, некоторые только в ООП, но в таком случае полезно делать аналогии с ФП. Поэтому я считаю, что полезнее всего она будет как раз для того кто почти не знаком с ООП. Например, я когда читал не был знаком. И C++ не знал, как и теперь все еще не знаю, так как там он используется как "псевдокод", абстрактный универсальный язык. Не скажу что я стал экспертом в ООП, и у меня никто не требовал этих знаний при сдачи книги. Согласен, что твой аргумент @olegromashin валидный, если для сдачи требуют знаний ООП, или C++, но таких требований нет.

**Comment by olegromashin** [comment]
Здесь я пишу в контексте того, что было мною прочитано и что не пересекается с ремеслом. На текущий момент прочитал только 2 части, вот полезная тема - это ООП, но в кейсе нашей карты развития то, как эта тема раскрывается, я думаю, не совсем к месту. По поводу остальной части книги не могу судить)

**Comment by Znack** [comment]
> вот полезная тема - это ООП, но в кейсе нашей карты развития то, как эта тема раскрывается, я думаю, не совсем к месту

@olegromashin а можешь тут плиз раскрыть мысль? :)

**Comment by Znack** [comment]
Мне очень понравилось, как @stanislav-az подробно расписал пункты, которые ему были полезны из книги (как "Accidential and essential complexity" и тд). У меня есть предложение, что может книгу убрать как обязательный пункт для сдачи у третьего мидла, но совместно составить вот такой список, что было полезного у Макконнелла и чего не было у Гудлифа так же хорошо раскрыто, и эти темы отдельно добавить как вопросы, и просто соответствующие главы книги сделать как один из ресурсов к этим вопросам.

То есть "Сопряжение и Связность" и "Инкапсуляция, абстракция, сокрытие информации" унести на [первого мидла сюда](https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/middle-1/design.md), там уже есть соответствующие вопросы, просто добавить в источники главы Макконнелла, где про это говорится. Некоторые темы (как "Accidential and essential complexity") если я правильно помню, у нас в карте нигде больше не встречаются, их надо отдельно просто вопросами добавить и тоже в источниках конкретные главы Макконнелла добавить (и желательно еще пару статей).

**Comment by olegromashin** [comment]
> > вот полезная тема - это ООП, но в кейсе нашей карты развития то, как эта тема раскрывается, я думаю, не совсем к месту
> 
> @olegromashin а можешь тут плиз раскрыть мысль? :)

Ну собственно аргументы те же, что и выше.
Вот иду я по карте развития, мне говорят: "Есть инкапсуляция, наследование и полиморфизм. Применяя классы ты можешь строить архитектуру вот так. Наследовать классы можно так, инкапсулировать в классах лучше вот так, а полиморфизм достигается шаблонами."
Я думаю, что здесь тот, кто идёт по карте развития, не может в полной мере понять повествование и вынужден выуживать какие-то куски и как-то составлять картинку в голове.
Более менее абстрагироваться от C++ у меня получилось только при чтении про инкапсуляцию. Я не считаю, что просто проведение каких-то аналогий и смутное представление об ООП стоит затраченного времени. Я был бы более удовлетворён, если бы мне надо было написать проект на ОО языке. А с тем кол-вом времени, которое я трачу сейчас относительно того, что я получаю, мне его жалко.
Опять же, это не про всю книгу, а только про ООП часть :)
Остальная часть, из того что я прочитал, просто повторяет Ремесло.

**Comment by Znack** [comment]
> Я думаю, что здесь тот, кто идёт по карте развития, не может в полной мере понять повествование и вынужден выуживать какие-то куски и как-то составлять картинку в голове.

Ну вот это валидный поинт. Стасу, например, я явно проводил аналогии, что класс можно условно сравнивать с модулем, а каждый метод класса с функциями в этом модуле, таким образом можно большинство из идей ООП переложить на ФП, но эту аналогию действительно надо объяснять, сама по себе она не возникнет :( Возможно, что явно проработав этот момент, прочтение Макконнелла для фп-ников станет более полезным 😄

**Comment by olgaklimenko** [comment]
> Начнем с того, что когда я сдавал Макконнелла хотел его полностью убрать из карты тоже :D Я спорил с @Znack что это все не нужно на карте развития для ФПшника. Но уже после сдачи у меня прошло отвращение к ООП, и только некоторые разделы книги в итоге были записаны в бесполезные.
> Ремесло программиста я не читал, содержание не смотрел, но если там обсуждаются точно такие же вещи как у Макконнелла, то может быть стоит оставить одну книгу. Вот самые интересные моменты из Макконелла, если их нет в ремесле, на мой взгляд, нельзя убирать его:
> 
>     * Accidential and essential complexity
> 
>     * Инкапсуляция, абстракция, сокрытие информации
> 
>     * Сопряжение и Связность
> 
>     * Ошибки: устойчивость, или корректность
> 
>     * Закон Парето 80/20
> 
>     * Итеративный и последовательный процесс проектирования
> 
>     * Восходящее / нисходящее проектирование
> 
>     * Стратификация при проектировании
> 
> 
> Думаю хейт ООП не обоснован, тем более что ты его вроде кодил на C++) Когда ты читаешь, нужно абстрагироваться от ООП, и проводить параллели с ФП. Если это сделать, то общие вещи для ООП и ФП выделяются в принципы написания хорошего кода как раз) И вообще, полезно иметь кругозор, как нельзя замыкаться только в ООП, так и только в ФП.
> 
> И еще вот разделы, которые я думаю можно убрать:
> 
>     * 13.2. Указатели
> 
>     * 17.3. Оператор goto
> 
>     * 26.2. Циклы
> 
>     * 31 Форматирование и стиль

Я хотела написать когда только пошло обсуждение, но Стас на тот момент уже успел перечислить все главы, которые на мой взгляд тоже стоит оставить. Также, я думаю, что здравая идея просто добавить Макконнелла на 1го мидла как источник.

**Comment by Nelliza** [comment]
Плюсую ребятам за то, чтобы убрать эти 2 главы:
- **13.2. Указатели**
- **17.3. Оператор goto**

Также считаю, что вполне можно выпилить последние главы:
- **33. Личность** — тут в основном субъективщина, имхо, к тому же эти вопросы освещаются и у Гудлифа
- **34. Основы мастерства** — здесь дублируется все ранее написанное, основные постулаты. Скорее всего, автор руководствовался принципом "повторение — мать учения". Но учитывая, что каждый из этих постулатов итак неоднократно упоминается в книге, в контексте этой главы такое дублирование показалось мне избыточным

**Comment by iatsdotfatr** [comment]
> * **33. Личность** — тут в основном субъективщина, имхо, к тому же эти вопросы освещаются и у Гудлифа
> * **34. Основы мастерства** — здесь дублируется все ранее написанное, основные постулаты. Скорее всего, автор руководствовался принципом "повторение — мать учения". Но учитывая, что каждый из этих постулатов итак неоднократно упоминается в книге, в контексте этой главы такое дублирование показалось мне избыточным

Если группа больше двух человек, то кому-то будет нечего рассказывать)

**Comment by olegromashin** [comment]
> * Accidential and essential complexity
> 
> * Инкапсуляция, абстракция, сокрытие информации
> 
> * Сопряжение и Связность
> 
> * Ошибки: устойчивость, или корректность
> 
> * Закон Парето 80/20
> 
> * Итеративный и последовательный процесс проектирования
> 
> * Восходящее / нисходящее проектирование
> 
> * Стратификация при проектировании

Прочитал и сдал Совершенный код. Исключил из твоего списка то, что есть у Гудлиффа. Вот что получилось:
- Accidential and essential complexity - Раздел 5.2, но вроде автор не разделяет сложность на accidential и essential.
- Связность - Это понятие в книге не выделяется как фундаментальное и про него нет отдельной главы. Там в одном абзаце дано определение и походу книги его применяют. Не уверен, что можно выделить какую-то главу, лучше посмотреть другой источник, если в карте на мидле нигде про такое нет.
- Принцип Парето - Раздел 25.2
- Стратегии проектирования - Раздел 5.4
Вроде это то, чего нет у Гудлиффа. Можно добавить материалы по интеграции - глава 29. Ещё мне понравилось про оптимизацию: глава 25. Но не куча примеров о том, в каком языке что быстрее, а мысль о том, что никогда, даже когда ты уверен на 100%, нельзя заранее сказать скажется оптимизирущее изменение положительно или отрицательно, всегда надо сравнивать.

**Comment by kelizarov** [comment]
У Гудлиффа в основном книга о мастерстве программирования. Поэтому я думаю из Совершенного Кода лучше выделить те главы, которые затрагивают более высокоуровневые темы в разработке. А именно:

* Глава 2 Метафоры, позволяющие лучше понять разработку ПО - сама идея об использовании метафор в разработке, чтобы проще описать проблему;
* Глава 3 Семь раз отмерь, один раз отрежь: предварительные условия - тут дается информация о важности выполнения пред-условий перед разработкой проекта, и какие риски они влекут за собой, сбор требований итд;
* Глава 5 Проектирование при конструировании - у Гудлиффа тоже есть про проектриования и архитектуры, но здесь мне кажется гораздо развернутее описаны разные виды проектирования проектов, с примерами;
* В целом вся V часть имеет информацию по делу, и раскрывает чуть глубже чем Ремесло. Я думаю ее можно бы полностью оставить.

Остальные главы немного спорные чтобы делать обязательными, так как многие из них очень заточены под временный промежуток, когда они были действительно выжны. Многие из них повторяют то что уже было сказано в Ремесле, но чуть более глубоко, поэтому их бы я оставил по-желанию. Мне кажется что в карте лучше оставлять информацию и ресурсы более общего назначения, а все детали можно изучить по мере требований (проектов, задач, личных целей).

**Comment by olegromashin** [comment]
Ну я думаю мы сошлись на том, что всю книгу оставлять смысла немного. Будем переносить необходимые главы и добавлять вопросы по ним в разделы по проектированию на мидлах.

**Comment by olegromashin** [comment]
Созвонились некоторое время назад. Пока руки не доходят взяться за решение, зафиксирую тут.
Пришли к тому, что будем убирать книгу из карты и создадим раздел на третьем джуне, погружающий в проектирование. В описании к разделу так и напишем, что темы надо спрашивать поверхностно. Совершенный код добавим как опциональный источник.

**Comment by olegromashin** [comment]
Начинаю. Когда обсудим то, что получается, создам ПР. Принимаются предложения и критика. Также инглиш можно проверить.

Basic principles of coding and design

The Goal:
Consolidate most important and common coding principles for all programming languages. Get acquainted with basic notions of design. All design questions do not require detailed answers. This topic implies preparation for [basic design principles](https://github.com/fullstack-development/developers-roadmap/blob/master/shared/middle-1/design.md).

Coding:
What are magic numbers and why they are bad?
Is it important to write code with maximum optimization? When you have to start thinking about forcing optimization? Why?
Why it is important to test code? What are black-box testing and white-box testing?
What is the difference between the following types of testing: unit testing, component testing, integration testing, regression testing, system testing?

Design:
Why it is important to think over requirements in advance? Is it possible to overdo it?
Explain the following forms and approaches of design: Iterate, Divide and Conquer, Top-Down and Bottom-Up design approaches.
What is Complexity? What is the difference between Accidental Complexity and Essential Complexity?
What is Cohesion?
What is Coupling?

Ещё подумываю добавить вопрос про персистентность. Как считаете?
