### ISSUE TITLE
jun1/haskell: сделать яснее некоторые вопросы

### ISSUE THREAD

**Issue by aoriens** [fullstack-development/developers-roadmap#265]
Привет. Мне кажется, некоторые вопросы в `jun1/haskell` неясны. Давайте подумаем, как их переформулировать, и я закину PR.

> What is associativity of operators?
> What is associative property? Does function application has that property?

Трудновато понять, о чем второй вопрос. Позже дошло, что он может быть о том, ассоциативно ли применение функций:

    -- это одно и то же?
    (a b) c 
    a (b c)

Путаницы добавляет то, что в первом вопросе имеется в виду другая ассоциативность - синтаксическое свойство инфиксного оператора (infixr, infixl, infix).

А нужен ли второй вопрос? Предлагаю его удалить, поскольку непонятно, какое знание он проверяет. Любому очевидно, что `a(b(c))` не то же самое, что `(a(b))(c)`, даже типы отличаются. Если вы хотите его оставить, то как насчет такого: Is the function application syntax associative? In other words, is `(a b) c` identical to `a (b c)`?

> Immutable data: 
> [...]
> Can you give some examples for the record and the list?

Наверное, он задается в контексте предыдущего, "How can you update values in immutable data structure?". Предлагаю дополнить:

Can you give some examples of updating a value of a record type and a list value?

> What does instantiation of a type variable mean? Does it happen at run time or at compile time?

Вот тут я надолго завис :). instantiation в словарях переводят как "создание экземпляра", "инстанцирование" - а при чем тут type variables? Фразы про type variable instantiation удалось нагуглить, но не понять. Я еще подумал и догадался, что тут имеется в виду подстановка типов во время тайпчека.

Вопрос правильный, но я думаю, пригодятся материалы для изучения.

**Comment by kelizarov** [comment]
Я в целом согласен со всеми пунктами. 

С функцией применения у меня тоже сомнения были а нужно ли вообще спрашивать. Вопрос из разряда интересных фактов, которые мало влияют на понимание языка и как работать на нем.

**Comment by wixe** [comment]
> > What is associativity of operators?
> > What is associative property? Does function application has that property?

Первый вопрос из второго пункта имхо повторяет вопрос из первого пункта и его можно убрать. По поводу function application часто неочевидно что имеется ввиду пробел, а не `$`, пару раз это вызывало путаницу, так что надо бы это удочнить

> Путаницы добавляет то, что в первом вопросе имеется в виду другая ассоциативность - синтаксическое свойство инфиксного оператора (infixr, infixl, infix).

Да ассоциативность то разной не бывает, это математическое понятие. Но пробел это не оператор в смысле хаскеля (хотя тут мб не прав), и понятие хаскелевской ассоциативности к нему не применимо. Поэтому может и стоих их разделить, но тут я не уверен.

> Любому очевидно, что ...

Так про многие вопросы можно сказать))

> Is the function application syntax associative? In other words, is `(a b) c` identical to `a (b c)`?

То что пробел ассоциативен было понятно из вопроса, а вот какая ассоциативность -- правая или левая, это предстояло ответить. А тут формулировка противоречит сама себе, потому что на первый вопрос ответ "да, левоассоциативна", а на второй "нет, это разные вещи", хотя между ними стоит эквивалентность в виде __in other words__. Я бы предложил оставить "What is the associativity of the function application" но гдето в доке надо всеравно уточнить что под FA подразумевается пробел, а не `$`.

Со всем остальным в целом согласен

**Comment by aoriens** [comment]
> Первый вопрос из второго пункта имхо повторяет вопрос из первого пункта и его можно убрать
> Да ассоциативность то разной не бывает, это математическое понятие.

Ассоциативность "первого" типа -- синтаксическая. Haskell Report в разделе про fixity declarations прямо использует слово associativity, так что я это не придумал. Она бывает left, right и none. Это значит, что:
- для левоассоциативного оператора, например, (+), `a + b + c` трактуется как `(a + b) + c`
- для правоассоциативного оператора, например, (.): `a . b . c` трактуется как `a . (b . c)`
- для неассоциативного оператора, например, (==), `True == True == True` не компилируется, нужно явно поставить скобки.

Ассоциативность "второго" типа другая, назовем ее математическая. Это такое свойство функции f, что выполняется ``(a `f` b) `f` c == a `f` (b `f` c)``.

Синтаксическая ассоциативность про то, как парсить выражения, а математическая -- про поведение конкретной функции. Они не связаны. Оператор сложения синтаксически левоассоциативен, а математически просто ассоциативен. Вычитание синтаксически левоассоциативно, а математически неассоциативно.

Так что эти вопросы немного о разном, и первый вопрос убирать не стоит. Почему мне кажется, что второй вопрос не нужен:
- если он про синтаксическую ассоциативность, то вопрос правомерный, но я не понимаю, чем полезно знание ответа. Кто-то сомневается, что `a b c` парсится как `(a b) c`? Стажер доходит до собеседования после двух приличных тестовых проектов и ревью. Он не напишет проекты, если не поймет синтаксис применения функций и каррирование. А поймет он быстро, или будет без конца получать ошибки компиляции.
- если про математическую, то, опять же, неужели человек, осиливший стажировку, не знает, что `(a b) c` не то же самое, что `a (b c)`? Это даже по типам не сойдется, тут и Хаскель никакой не нужен, возьмите любой язык. А еще вопрос выглядит не на месте. Рядом вопросы о синтаксисе и семантике выражений, и тут бац, вопрос о математических свойствах оператора применения.

Если нужно оставить этот вопрос, то давайте определимся с его смыслом, а дальше будет видно, как переформулировать.

> По поводу function application часто неочевидно что имеется ввиду пробел, а не $, пару раз это вызывало путаницу, так что надо бы это удочнить

Можно function application syntax. Хотя в Haskell Report пишут просто function application.

> Но пробел это не оператор в смысле хаскеля (хотя тут мб не прав), и понятие хаскелевской ассоциативности к нему не применимо.

У него левая ассоциативность: `a b c` парсится как же, как `(a b) c`.

**Comment by olegromashin** [comment]
По поводу математического свойства ассоциативности согласен, можно выпилить. Тем более про него всё равно надо будет рассказать как про закон моноидов.

Про иммутабельность не уверен, что последний вопрос вообще нужен. Если сдающий ответил правильно на всё перед этим, то он просто покажет как добавить элемент в список и как изменить поле у значения с типом с рекордами, а это уже проверяется в других разделах.

На счёт instantiation я, кстати, сталкивался с такой же проблемой при подготовке. Как вам такой вариант?

> How does process instantiation of a type variable happen, i. e. how does type variable become regular type? Does it happen at run time or at compile time?

Мне не хочется слово instantiation выпиливать, я его встречал в англоязычной документации в других областях разработки и хотелось бы, чтобы оно не вызывало затруднений :)

**Comment by aoriens** [comment]
> На счёт instantiation я, кстати, сталкивался с такой же проблемой при подготовке. Как вам такой вариант?
> 
> > How does process instantiation of a type variable happen, i. e. how does type variable become regular type? Does it happen at run time or at compile time?

Мне так больше нравится. Но для этого вопроса стоит подыскать источник, вопрос сложно гуглится.

**Comment by olegromashin** [comment]
> Мне так больше нравится. Но для этого вопроса стоит подыскать источник, вопрос сложно гуглится.

Ну я бы не сказал, что здесь нужна какая-то теория. Вопрос, скорее, на просто догадаться. Я, конечно, не против добавить источник, но думаю, что вряд ли это где-то сформулировано отдельно. Довольно логичная и простая штука, которую не должно составить труда объяснить, если вопрос грамотно составить.
Кстати, наверное, артикль `a` надо добавить перед словосочетанием `regular type` в моём вариаенте.

**Comment by aoriens** [comment]
Итого:

- вырезаем `What is associative property? Does function application has that property?`
- вырезаем в разделе про иммутабельность `Can you give some examples for the record and the list?`
- вопрос про instantiation переформулируем в `How does instantiation of a type variable happen, i. e. how does the type variable become a regular type? Does it happen at run time or at compile time?`
- я добавляю источник для предыдущего вопроса, если найду

Еще вопрос:

> What is function application operator? And what is its precedence value?

На ум приходит оператор `$`, потому что `operator`, но по контексту здесь скорее о синтаксисе применения функций, который пробел. Предлагаю убрать слово `operator` и, возможно, добавить `syntax`. Можно спорить о том, является пробел оператором или нет, но операторность `$` ни у кого сомнений не вызывает :), так что путаница вероятна. В Haskell Report это называется просто `function application`, без `operator`.

**Comment by stanislav-az** [comment]
> вырезаем What is associative property? Does function application has that property?

С этим не согласен. Вопрос для того, чтобы все понимали разницу между синтаксической ассоциативностью и математическим свойством. 
> Он не напишет проекты, если не поймет синтаксис применения функций и каррирование.

Тут еще важно чтобы все могли применять принятую терминологию и правильно явно озвучить эти неявные интуитивные знания.
> неужели человек, осиливший стажировку, не знает

Часто если о чём-то не задумываться, а просто делать чтобы работало, знаний все равно не появится. Опыт и знания это же в общем-то разные вещи.

**Comment by stanislav-az** [comment]
> What is function application operator?

Думаю, можно здесь спросить и про пробел и про $, и про &. "What are three function application operators?" Ну или явно их перечислить и спросить зачем они нужны.

**Comment by stanislav-az** [comment]
> вырезаем в разделе про иммутабельность Can you give some examples for the record and the list?
вопрос про instantiation переформулируем в How does instantiation of a type variable happen, i. e. how does the type variable become a regular type? Does it happen at run time or at compile time?
я добавляю источник для предыдущего вопроса, если найду

В остальном согласен. Спасибо за исправления :)

**Comment by aoriens** [comment]
> > вырезаем What is associative property? Does function application has that property?
> 
> С этим не согласен. Вопрос для того, чтобы все понимали разницу между синтаксической ассоциативностью и математическим свойством.

А так подойдет? `Is the function application syntax associative? In other words, is (a b) c identical to a (b c)?`

> > What is function application operator?
> 
> Думаю, можно здесь спросить и про пробел и про $, и про &. "What are three function application operators?" Ну или явно их перечислить и спросить зачем они нужны.

Пробел не является оператором в полном смысле, поэтому к нему лучше не применять слово `operator`, это запутает людей. Хотя у него есть признаки оператора (fixity), он не настолько оператор, как `$`.
Оператор `&` редко встречается, не в каждом учебнике. Если иметь его в виду, нужно добавить ссылку на `Data.Function`.

**Comment by stanislav-az** [comment]
> Оператор & редко встречается, не в каждом учебнике

Ну обычно его с линзами используют, джуну-1 может и не очень полезно.

> А так подойдет?

Вроде хорошо.

> Пробел не является оператором в полном смысле

Да, хорошо, тут наверное нельзя термин "оператор" применять. Ну тогда можно спросить как можно применять функцию и зачем существуют разные способы.

**Comment by aoriens** [comment]
> Да, хорошо, тут наверное нельзя термин "оператор" применять. Ну тогда можно спросить как можно применять функцию и зачем существуют разные способы.

Вопрос, зачем `$`, уже есть. Про `&`, я так понял, решили не спрашивать (а если спрашивать, ответ мало отличается от такового про `$`). Остается обычный function application - тогда, может быть, оставим вопрос как есть, лишь убрав `operator`?

`What is function application? And what is its precedence value?`

Как думаете, легко ли понять его неправильно, будто спрашивают про `$`? Лично мне кажется, что нет.
`function application syntax` не хочу писать, так как применение функции это больше, чем синтаксис. Это еще элемент вычислений.

**Comment by olegromashin** [comment]
> What is function application? And what is its precedence value?

Я думаю я бы неправильно понял. Кстати, когда я сдавал теорию, то про пробел нигде не читал, и мне это рассказали прямо на сдаче.

Давайте уберём вопрос `Why does $ operator exist?` и заменим вопрос `What is function application operator? And what is its precedence value?` на `There are three ways to apply function: space, $ and &. What is the difference between them?`. Про амперсанд на степике есть, + на нашем проекте он повсеместно используется, лишним не будет.

**Comment by aoriens** [comment]
> и заменим вопрос `What is function application operator? And what is its precedence value?` на `There are three ways to apply function: space, $ and &. What is the difference between them?`

Можно поправить мелочи:

There are many ways to apply a function: `f x` syntax, `$` operator, `&` operator, etc. What is the difference between them? Why do they exist? What is their fixity?

Слово space расплывчато, и я не встречал его в источниках по хаскелю. Перевести можно не только как "пробел", но и "космос", "пространство" :). 
Способов применять функцию много, и вообще это долгий и ненужный вопрос, что считать "отдельным способом применения функции", поэтому `three -> many`.
Вопрос "в чем между ними разница" слишком общий, кандидат может не догадаться, чего от него хотят. В старых вопросах спрашивалось об их fixity, поэтому и здесь стоит.
Поскольку предлагается убрать вопрос о назначении `$`, добавил `Why do they exist?`. Мелочь, конечно, но важная.

**Comment by olegromashin** [comment]
Про `space` какая-то надуманная проблема, как по мне) мы в речи и в тексте постоянно используем слова, у которых несколько смыслов. Здесь из контекста вполне понятно. Ну это так, ради справедливости, ничего не имею против твоего варианта :)
