### ISSUE TITLE
[Обсуждение] jun2/linux: вопросы про симлинки, man & less

### ISSUE THREAD

**Issue by vkpgwt** [fullstack-development/developers-roadmap#285]
Хочется узнать ваше мнение насчет новых вопросов в jun2/linux.

1. Симлинки и хардлинки. Файлы устройств (достаточно знать об их существовании).
2. man-страницы. Работа в `man` и `less`.

Вопрос о линках кажется логичным продолжением вопроса о правах файлов. Знание симлинков помогает пользоваться системой, писать скрипты. Хардлинки в явном виде нужны редко, но их знание помогает понять, что такое inode, безымянные временные файлы, почему файл может быть удален, будучи открытым, и почему линукс не нужно перезагружать после обновления. 

В юниксах хорошая справочная система - man-страницы. Ими проще и быстрее пользоваться, чем гуглом, и они содержат актуальную инфу, в отличие от случайной страницы в выдаче гугла. Юниксы бывают очень разные, с мелкими различиями в командах и опциях. Проблема в том, что надо знать определенные команды и хоткеи пейджера `less`, хотя бы для того, чтобы закрыть :). Тут как с вимом.

**Comment by olgaklimenko** [comment]
1. Про `symlink` поддерживаю добавление, интересно будет знать. Не уверена, что стоит на 2го джуна это добавлять, я на практике редко встречаю надобность (в последний раз при настройке nginx). У нас есть еще линукс на мидла, может стоит туда положить, т.к. на 2м джуне мы старались оставить вопросы для совсем новичков в линуксе. 

2. Про `man` и `less` кажется спорно учить команды для собеса. Можно вбросить пару вопросов для чего нужен инструмент, чтобы человек знал о возможности использования. Иначе может получиться, что юзать будет почти никто, а зубрить для собеса придётся всем.

**Comment by olgaklimenko** [comment]
Сейчас вот подумала, что на 2м джуне точно пригодятся вопросы про переменную `PATH` и про экспорт временный и постоянный. Часто встречается при настройке рабочего окружения. Здесь пока оставлю, раз тут тема по линуксу, можно сразу обсудить.

**Comment by aoriens** [comment]
>  Про man и less кажется спорно учить команды для собеса. Можно вбросить пару вопросов для чего нужен инструмент, чтобы человек знал о возможности использования. Иначе может получиться, что юзать будет почти никто, а зубрить для собеса придётся всем.

Я думал добавить примерно такие вопросы:
1. Как искать справочную информацию о команде? (1 команда)
2. Как искать справочные страницы по ключевым словам? (100 лет не использовал эту опцию. Может, и не надо).
3. Хоткеи пейджера man/less: как скроллить вверх-вниз, как выйти, как найти строку по регекспу, как найти следующее-предыдущее совпадение. Думаю, не стоит их спрашивать, лучше оставить шпаргалку на видном месте.

Вроде немного. По существу 1 вопрос и опциональных 1-2.

Насчет того, что никто не использует - может, потому и не использует, что не знает о такой возможности? Ведь и в чеклисте приводятся ссылки на туториалы по команде `ps` в интернете, а не на `man ps`. Человеку неоткуда узнать, что у него в систему встроена необходимая документация и ничего гуглить не надо.

Если люди знают про man и все равно предпочитают гуглить - ок, тогда не стоит спрашивать про man. Лично мне man кажется удобнее, быстрее и точнее гугла, но, возможно, это индивидуально.

**Comment by olgaklimenko** [comment]
Как раз 1й вопрос позволяет показать, что инструмент существует, его надо включить в карту. А остальное на мой взгляд лучше оставить уже на ресерч по желанию (например просто добавить опциональные ссылки на ресурсы). Про ссылки на туториалы: по идее нам не важно, откуда человек будет узнавать информацию о командах, можно использовать любые достоверные источники для подготовки к собесу, так что можно man тоже в источники добавить :)

**Comment by aoriens** [comment]
Итог:

1. Добавляем один вопрос про `man`
2. Добавляем симлинки-хардлинки в linux middle
3. Добавляем про переменные среды, export & ~/.profile, переменную PATH.
