### ISSUE TITLE
Добавить вопросы на первого мидла

### ISSUE THREAD

**Issue by clicktronix** [fullstack-development/developers-roadmap#29]
Можно начать с блока ООП, там не все надо на middle-1 переносить сюда, так как некоторые темы уйдут на middle 2.

## ООП
- Книга Мэтт Вайсфельд «Объектно-ориентированное мышление» (это вводная по ооп как раз)
- Что такое ООП (что такое иерархия классов, чем композиция отличается от наследования)
- Что такое класс?
- Что такое объект?
- Что такое абстрактный класс и абстрактный метод?
- Какие особенности у каждого из основных типов отношений между классами: композиции, агрегирования, наследования, ассоциации?
- Что такое принципы SOLID? Что означает каждая буква из акронима?
- Надо ли бороться с сайд-эффектами при проектировании в парадигме ООП?
- Являются ли мутации сайд-эффектом?
- Что такое статический метод? Является ли класс только из статических методов классом по ООП?

## ФП
- Что такое чистая функция?
- Что такое ссылочная прозрачность? Является ли это свойство достаточным признаком чистоты функции?
- Что такое идемпотентность?
- Почему функциональное програмирование считается "декларативным"?
- Может ли из чистой функции произойти вызов грязной? Если да, то что это значит?
- Какие преимущества иммутабельных структур данных?
- Как сделать работу иммутабельных структур данных быстрой?
- Как реализовать функцию compose?
- Что такое рекурсия? 
- Что такое оптимизация хвостового вызова и поддерживается ли она в JS?

## Структуры данных
Перенести и расписать в форме вопросов по каждой структуре из нашего текущего списка, а не просто перечислить, как у нас там

**Comment by Znack** [comment]
Я бы кстати сюда Генераторы и итераторы перенес, потмоу что это довольно конкретная вещь, не сильно сложная, к тому же очень вяжется с асинхронностью, которая тоже на этом уровне остается. Что думаете @clicktronix @kinda-neat @in19farkt @chmnkh ?

**Comment by clicktronix** [comment]
И async await еще) но тогда и про корутины вопрос сюда перейдет

**Comment by Znack** [comment]
Да, на втором мидле эти вопросы уже поздно спрашивать, по хорошему тут стоит, поэтому давай перенесем. 

> Что такое async/await?
> Как провести аналогию генераторов с async/await?
> Как обрабатывать ошибки в коде, использующем внутри себя await?
> Что, если функция, которая была вызвана с await, сама по себе не асинхронная? (как это сэмулировать для начала?)
> Как запустить выполнение нескольких асинхронных функций (созданных через async) и дождаться их общего выполнения?

**Comment by kinda-neat** [comment]
вся асинхронность переезжает сюда? вплоть до вопросов а-ля "провести аналогию async/await с генераторами?"

**Comment by clicktronix** [comment]
ну начало у тебя будет в старшем джуне по сути. С промисами с колбэками

**Comment by Znack** [comment]
Ну пока я не до конца решил, на втором-третьем мидлах тоже будет скорее всего, но ещё более продвинутые темы. async/await и сравнение с генераторами точно тут надо, да

**Comment by GoodDayTodayOkey** [comment]
У меня вопрос, который может существенно повлиять на разбиение вопросов. https://github.com/fullstack-development/developers-roadmap/tree/master/frontend  Исходя из структуры по фронтенду, текущий старший джун разделится на две части, мидлов же 4, при текущих трех на риззоме, следовательно только одного из будут делить? Это второй текущий миддл? Если так то получится что все категории кроме первого мидла будут в два раза дешевле по оплате? (тут я могу ошибаться поправьте меня если не прав). Если так, то возможно стоит и первого текущего разделить на две части? Тогда необходимо заранее обсудить какие вопросы пойдут в какаю часть.

**Comment by GoodDayTodayOkey** [comment]
У меня вопрос, который может существенно повлиять на разбиение вопросов. https://github.com/fullstack-development/developers-roadmap/tree/master/frontend  Исходя из структуры по фронтенду, текущий старший джун разделится на две части, мидлов же 4, при текущих трех на риззоме, следовательно только одного будут делить? Это второй текущий миддл? Если так то получится что все категории кроме второго текщуего мидла будут в два раза дороже по оплате? (тут я могу ошибаться поправьте меня если не прав). Будут ли происходить деление первого мидла или третьего? Тогда необходимо заранее обсудить какие вопросы войдут в какаю часть.

**Comment by Znack** [comment]
Касательно оплаты и тд — это точно не на гитхабе обсуждать, Валентин :)

Касательно деления — сейчас по большей части поделили младшего мидла как раз, а новый второй мидл стал объединением остатка младшего мидла с небольшим добавлением среднего.

**Comment by GoodDayTodayOkey** [comment]
А в чем заключается деление младшего мидла? Насколько я понял из выше описного сюда переедет часть ООП, добавятся  вопросы по ФП и часть асинхроннности.

**Comment by Znack** [comment]
Да, сейчас в млад мидле есть довольно сложные вещи по ООП и слишком высокоуровнвые по ФП, которые хорошо бы разбить. Плюс паттерны перенесли на второй уровень и тд. Короче, сделать первого мидла с базовыми концептуальными вещами, а не сразу продвинутым
