### ISSUE TITLE
Junior-3. Haskell - Extensions

### ISSUE THREAD

**Issue by olegromashin** [fullstack-development/developers-roadmap#291]
В результате сдачи экстеншенов накопилось несколько исправлений, которые хотелось бы внести.

1. Убрать раздел Types, в котором сейчас 1 вопрос: "Что такое кайнд?". Это спрашивается в DataKinds, хотя там про конкретный кайнд *, а здесь общий вопрос. Можно и перенести.
2. Добавить DerivingVia в часть с Deriving.
3. Добавить источник в Type and Data Families: https://stackoverflow.com/questions/49433716/why-cant-we-define-closed-data-families

Will be continued...

**Comment by aoriens** [comment]
- предлагаю добавить ссылку в раздел гадтов об их связи с тайпклассами: https://stackoverflow.com/questions/10994508/gadts-vs-multiparamtypeclasses
- RankNTypes и экзистенциалы я бы поставил раньше гадтов и type families, потому что экзистенциалы упоминаются в описании гадтов и их проще понять.
- списки литературы хорошо бы расположить поближе к соответствующим темам. Каты тоже - они в самом конце.
- возможно, добавить ссылки про type families. Я их записал, но в итоге не понадобились:
  - суперпростой гайд, но мне не понравился, слишком мало пояснений: https://cdepillabout.github.io/haskell-type-families-presentation/#/
  - еще один, но сложнее, я не дочитал. Оцените, может, понравится: https://ocharles.org.uk/blog/posts/2014-12-12-type-families.html
- вопрос про standalone deriving предлагаю поставить после гадтов и экзистенциалов. Дока по StandaloneDeriving довольно большая и описывает дерайвинг для гадтов, что важно. Поэтому до изучения гадтов читать ее менее полезно, хуже запомнится.
- непонятен вопрос про inconvenience between term level & type level of promoted kinds. Кажется, имелось в виду, можно ли написать функцию из значений в соответствующие promoted values или наоборот. Предлагаю так и сформулировать.
- трудно ответить на вопрос, как constraint kinds помогают generic programming, если не умеешь дженерики. Дженерики это тема на мидле. В #287 предложил перенести весь ConstraintKinds на мидла. Если будет решено оставить раздел как есть, тогда предлагаю удалить вопрос или переформулировать так, чтобы его было куда пристроить на мидле.

**Comment by vkpgwt** [comment]
Вопрос `What is a "rank" of a function?` предложили то ли убрать, то ли переформулировать.

**Comment by kelizarov** [comment]
> суперпростой гайд, но мне не понравился, слишком мало пояснений: https://cdepillabout.github.io/haskell-type-families-presentation/#/
еще один, но сложнее, я не дочитал. Оцените, может, понравится: https://ocharles.org.uk/blog/posts/2014-12-12-type-families.html

Я думаю оба стоит включить, они простые и довольно просто объясняют хотя бы базово для чего тайп-фэмили. Надо бы так же добавить ссылку на доку по тайп-фэмили.

**Comment by vkpgwt** [comment]
Предложили поправить laziness:
- добавить thunk:thunk в список выражений, для которых надо определить, в какой они форме
- вопрос про strict functions лучше переформулировать - тут имеются в виду функции с включенным расширением Strict.
- `Make examples when bang pattern has less power, than it could be supposed` - вопрос непонятен, можно спросить о том, до какой формы вычисляется bang pattern.

**Comment by vkpgwt** [comment]
Laziness.

Я запутался в куче синонимов для разных стратегий: outside in, inside out, lazy, call by value/name/need, нормальный порядок, аппликативный порядок, стратегии вызова (и чем они отличаются от стратегий вычисления?). По хорошему, достаточно 5 терминов: две редукции (нормальная, аппликативная), 2 стратегии вычисления и еще неиспользуемый call by name. А остальные термины свести к этим 5, если они обозначают то же самое.

Добавить вопрос про `(a+b) `seq` expr`.
Убрать ответ из последнего вопроса, где про Maybe :)

Еще нужно добавить вопрос, выявляющий знание, что let/where top level pattern bindings ленивые (irrefutable). Это единственный случай, когда паттерны ленивые по умолчанию, без знака `~`. И когда узнаешь факт того, что что-то ленивое по дефолту, это очень нервирует, приходится искать, вдруг они ленивые где-нибудь еще. Возможно, это надо спрашивать даже на jun2 или 1.

**Comment by Znack** [comment]
> Убрать ответ из последнего вопроса, где про Maybe :)

А там это не вопрос, там это объяснение задачи :) Может просто кривая формулировка "There is a ! inside a Maybe, which is inside a let expression, and let expressions are lazy:", здесь имеется в виду, что надо обратить внимание на ! внутри паттерн матчинга и как он себя ведет учитывая, что let-ы ленивые

**Comment by vkpgwt** [comment]
> учитывая, что let-ы ленивые

Это и есть ответ, не нужно этого писать :). "Вот есть bang pattern внутри let, форсирует ли он вычисление переменной?". Когда интервьюируемый добрался до этого вопроса, он усвоил, что bang patterns форсируют все подряд, а это вопрос-ловушка на исключение из данного правила, не надо подсказывать.

**Comment by Znack** [comment]
Неее, это всё таки не ответ, но то что жирный намёк я согласен :) давай уберём :)

**Comment by olgaklimenko** [comment]
добавить PolyKinds ресурс: https://kseo.github.io/posts/2017-01-15-data-proxy.html

**Comment by olegromashin** [comment]
>     * RankNTypes и экзистенциалы я бы поставил раньше гадтов и type families, потому что экзистенциалы упоминаются в описании гадтов и их проще понять

Субъективно. Мне намного труднее дались RankNTypes, я бы оставил.

>     * вопрос про standalone deriving предлагаю поставить после гадтов и экзистенциалов

По-моему лучше оставить как есть. Вроде спрашиваем сначала идейно, пока проблем не возникало. Ну и если перенести получится такая же ситуация, только наоборот. Придётся при изучении сложных экстеншенов читать про дерайвинг.

С остальным согласен.

**Comment by olgaklimenko** [comment]
Экзистенциалы все же луше перенести повыше, `rankNTypes` соглашусь, можноо ставить где они есть.

**Comment by olegromashin** [comment]
Ага, уже смёрджил, забыл упомянуть)

**Comment by olgaklimenko** [comment]
@antonkalinin-ml можешь предложение по laziness в отдельное ишью вынести?) А то тут по экстеншенам задача, и она уже сделана, мне кажется сюда никто не зайдёт уже, чтобы обсудить твоё предложение :)

**Comment by antonkalinin-ml** [comment]
@olgaklimenko @olegromashin перенес в https://github.com/fullstack-development/developers-roadmap/issues/309 , можно данную таску закрывать.
