### ISSUE TITLE
[Frontend/Middle-1/Async] Прояснить вопросы

### ISSUE THREAD

**Issue by iatsdotfatr** [fullstack-development/developers-roadmap#301]
> Что, если функция, которая была вызвана с await, сама по себе не асинхронная? Как это сэмулировать?

> Как осуществляется отлов событий в JS?

Сдавал тему. Ни я, ни принимающие не знали, как надо отвечать на эти вопросы :).

**Comment by Znack** [comment]
@chmnkh @alextsk @sk1e а вы помните, что обсуждалось на этих вопросах?

**Comment by chmnkh** [comment]
Мы с Серегой принимали. Без понятия, что это за вопросы, и зачем они нужны. 

Вообще топик надо чуть чуть проработать получше, у меня было пару мыслей, но пока руки не дошли, попозже отпишусь.
