### ISSUE TITLE
[Haskell] Добавить практически ориентированные вопросы по экстеншенам

### ISSUE THREAD

**Issue by stanislav-az** [fullstack-development/developers-roadmap#306]
У меня есть несколько файлов с небольшими заданиями, которые можно решить на сдаче уровня. Пока их решает человек как раз можно задавать вопросы на понимание, или наводящие вопросы. Могу добавить файлы с кодом и комментариями с вопросами к задаче. Вопрос в том, насколько это нужно?

**Comment by Znack** [comment]
О, круто! однозначно нужно :)
