### ISSUE TITLE
Revise Testing, Debugging resources

### ISSUE THREAD

**Issue by olgaklimenko** [fullstack-development/developers-roadmap#313]
**How MTL-style monad allows you to mock real implementation?**  -- убрать вопрос, или понять что конкретно тут спрашивается (MTL стайл это тот же Final Tagless).

**How can you pass dictionaries to switch the behavior of the program in various contexts?**  -- не очень понятный вопрос. Про то как определяется какие именно инстансы использовать для FT, какой именно сет функций для Handle, какую реализацию для Free Monad.

По **Free monad** предлагаю добавить [ресурс](https://www.endpoint.com/blog/2016/03/11/strict-typing-fun-example-free-monads), поверхностно описывающий паттерн (без описания библиотеки фри монад): 

Ресурсы, которые есть сейчас по тестированию не помогают ответить на вопросы. Можно добавить вопросы про декомпозицию и `MonadMock` или не добавлять и пометить ресурсы как опциональные.

**По дебагу:** добавить, что надо глянуть в сорцы, поглядеть как сделана `trace` функция.

**Comment by antonkalinin-ml** [comment]
> Ресурсы, которые есть сейчас по тестированию не помогают ответить на вопросы. Можно добавить вопросы про декомпозицию и MonadMock или не добавлять и пометить ресурсы как опциональные.

Там классные ресурсы, о различии мок-тестирования и state-тестирования, о том, как писать нехрупкие тесты. Но для них совсем нет вопросов. У нас не затронута в вопросах тема написания хороших юнит-тестов, терминологии (стабы, моки, etc), надо целый новый раздел заводить. Если у фронтенда этот раздел есть, можно что-нибудь взять оттуда. Давайте подумаем над этими вопросами. Сейчас нет времени их придумывать, но вообще я бы этой темой занялся, у меня самого дефицит знаний по этой теме и хочется его закрыть.

**Comment by Znack** [comment]
На фронтенде много интересного есть, я рекомендую вообще по умолчанию просто хотя бы фронтовые топики в shared вынести и с них можно прямо начать, там почти ничего специфичного для фронта, почти все и для бпкенда актуально :)
