### ISSUE TITLE
[Frontend, jun-1, JavaScript] Добавить вопросы по prototype

### ISSUE THREAD

**Issue by mglknFSD** [fullstack-development/developers-roadmap#318]
Столкнулся с проблемой, что в процессе подготовки к собеседованию, у стажеров проходит мимо понимание как устроена прототипная модель. И все уверены что свойство `.prototype` есть вообще у каждого объекта.

Предлагаю добавить вопрос.

`Свойство .prototype есть у всех объектов? Расскажите про свойство __proto__`

**Comment by iatsdotfatr** [comment]
Я бы первый вопрос переформулировал, типа: "Рассказать про свойство prototype. Чем отличается это свойство у функции-конструктора от аналогичного у обычного объекта?".
Если хочешь добавить / убрать вопрос или материалы к теме, лучше сразу открывать ПР и назначать ревьюеров.

**Comment by mglknFSD** [comment]
> Я бы первый вопрос переформулировал, типа: "Рассказать про свойство prototype. Чем отличается это свойство у функции-конструктора от аналогичного у обычного объекта?".

Да уже есть такой вопрос `Что такое прототип? Какие возможности имеет/дает?`.

**Comment by iatsdotfatr** [comment]
Так это, кажется, вопрос про систему наследования, а не про конкретные свойства. Можно "Рассказать про свойство prototype. Чем отличается это свойство у функции-конструктора от аналогичного у обычного объекта?" и "Рассказать про свойство __proto__" добавить к нему подвопросами.

**Comment by mglknFSD** [comment]
> 
> 
> Так это, кажется, вопрос про систему наследования, а не про конкретные свойства. Можно "Рассказать про свойство prototype. Чем отличается это свойство у функции-конструктора от аналогичного у обычного объекта?" и "Рассказать про свойство **proto**" добавить к нему подвопросами.

Тут нюанс вот в чем. Ты будешь копать про прототипное наследование для вопроса `Что такое прототип?`, и как при этом не покопать про само свойство `.protorype`? Неужели никто не копает эту инфу?  Да копают, конечно. Но вот где есть прототип а где его нету, почему-то никто не понимает. Все думают что он есть у любого объекта. Поэтому мое предложение именно с четким вопросом `У всех ли объектов есть прототип?`. Если стажер покопает именно этот вопрос картина в его голове будет более полной.
