### ISSUE TITLE
jun3 CSS 

### ISSUE THREAD

**Issue by a-poluhin** [fullstack-development/developers-roadmap#328]
Заметил не рабочую ссылку: "Разница между DPI и PPI"
![image](https://user-images.githubusercontent.com/10168007/135594786-2bd16b98-74d9-4d9a-b5eb-8a1a447794c0.png)

**Comment by Znack** [comment]
@a-poluhin давай пулл реквест сразу :) Может кстати где-то по другому адресу этот ресурс доступен или можно вообще альтернативную статью найти

**Comment by kate-fsd** [comment]
@a-poluhin можно заменить на эту https://artforlife.ru/stati-po-dizajnu/ppi-i-dpi-v-chem-raznitsa.html. Она и в выдаче поиска первая)
Еще предлагаю дополнить статью "Не используйте @import" этой ссылкой https://www.wirebox.co.uk/wp-content/uploads/2014/08/even-faster-web-sites-presentation1.pdf (слайды 37 - 42), в статье битые ссылки на картинки
