### ISSUE TITLE
Добавить пояснение в вопрос о создании массива (джун 1)

### ISSUE THREAD

**Issue by krashaen** [fullstack-development/developers-roadmap#33]
[Ссылка на вопрос](https://github.com/fullstack-development/developers-roadmap/blob/master/frontend/junior-1/js.md#%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B)
 
Сейчас вопрос звучит:

> Способы создания массивов (литерал, конструктор, фабричные методы)

Не первый раз вижу как ребята не понимали про то, в фабричных методах нужно рассказать про `Array.from()` и `Array.of()`.
Раз уж мы добавляем конкретики предлагаю явно это указать:

> Способы создания массивов (литерал, конструктор, фабричные методы `Array.from()` и `Array.of()`)

@Znack @chmnkh @GoodDayTodayOkey что думаете?

**Comment by Znack** [comment]
Да, хорошая тема
