### ISSUE TITLE
Стажировка, Haskell: лимитировать список форматтеров

### ISSUE THREAD

**Issue by antonkalinin-ml** [fullstack-development/developers-roadmap#344]
Предлагаю явно указать перечень форматтеров в стажировке по Haskell: ormolu, fourmolu, hindent. Либо только ormolu, дабы исключить вообще всякий выбор и душевные метания у стажеров на тему, какой форматирует красивее.

brittany не предлагаю, так как он не доделан, не форматирует инстансы и какие-то еще элементы.
hindent устарел, не самый красивый и немного глюкавый, но многие им уже пользуются по текущим требованиям. Если hindent успешно форматирует код - никаких проблем.

Некоторые выбирают stylish-haskell, который вообще не форматирует тела функций, его исключаем :).

Напомню, зачем нужен форматтер:
- для наведения читабельности в коде. Это не так важно, если стажер аккуратный.
- на некоторых (или большинстве?) проектах форматтер обязателен. Если наличие форматтера это непреодолимая проблема для человека, то лучше ему не тратить время на стажировку, или пусть свыкается с тем, что это обязательная часть будущей работы, и не возвращается к этому вопросу.

Напишите, пожалуйста, согласны ли со списком, следует ли что-нибудь добавить, и стоит ли оставлять один ormolu.

**Comment by kelizarov** [comment]
Предлагаю оставить только `ormolu` просто потому что его настраивать не надо.

**Comment by olgaklimenko** [comment]
Не думаю, что использовать форматтер для кого-то непреодолимая проблема, скорее всего стажёры просто забывают его запустить перед коммитом или невнимательно пробегают по требованиям из 5го задания. Можно добавить рекомендацию настройки автоформаттинга на сохранение файла, для тех кто знает, что склонен забывать запустить вручную.
Думаю лучше оставить один вариант - `ormolu`.

**Comment by antonkalinin-ml** [comment]
> Не думаю, что использовать форматтер для кого-то непреодолимая проблема, скорее всего стажёры просто забывают его запустить перед коммитом или невнимательно пробегают по требованиям из 5го задания. 

Такие люди есть, мы в чате обсуждали. Для них реально проблема использовать форматтер - пришлось уговаривать и дожидаться, пока он выберет самый кошерный.

**Comment by olgaklimenko** [comment]
Припоминаю 1 случай. Да, если человек принципиально отказывается форматировать, то он не сможет на проектах работать. Тут расширение списка форматтеров наврядли поможет, надеюсь редко будем встречать таких :)

**Comment by antonkalinin-ml** [comment]
Написал в программе про ormolu. Думал оставить hindent вторым вариантом для тех, кто уже привык, но сменить форматтер дело пяти минут, смысла нет.
