### ISSUE TITLE
[Frontend/jun1], дополнительные/уточняющие вопросы.

### ISSUE THREAD

**Issue by FanManutd** [fullstack-development/developers-roadmap#348]
Всем привет) В процессе приёма интервью у стажёров заметил, что есть довольно одинаковые дополнительные вопросы, которые передаются из уст в уста, из поколения в поколение так сказать) Решил формализовать эти вопросы, что бы для стажёров они не были неожиданностью, а интервьюерам не приходилось держать их в голове, и каждый раз спрашивать одно и тоже. Ниже приведу список, который я помню (предлагаемое дополнение будет выделено жирным) и попрошу всех желающих добавить, если я что-то упустил. После того, как обсуждение здесь закончится, создам ПР.

### HTML 
* Что такое doctype и зачем он нужен? **Что будет, если не написать doctype?**

### CSS
* Что делает свойство `margin`? Какие есть особенности у отрицательных значений? Что такое margin collapsing **и в каких случаях это происходит?** 
на моей памяти только один стажёр перечислил все 3 случая. Все остальные называли только один и шли читать про оставшиеся 2.

### JS

* Что значит создавать переменную через конструктор или через литерал? **Есть ли отличия?**

### Git
  * Как посмотреть список веток **(локальных и удалённых)**?
  * Как переименовать ветку **(локально и удалённо)**?
  * Как удалить ветку **(локально и удалённо)**?

Так же хочу упомянуть здесь несправедливо забытое ишью про `.prototype` #318 . Надо оживить обсуждение и принять решение, которое я добавлю в ПР. 
Сейчас вопрос про прототипы следующий: `Что такое прототип? Какие возможности имеет/дает?`
На мой взгляд, проблема не в том, что человек думает, что свойство `.prototype` есть у каждого объекта, а в том, что он в целом либо не знает про это свойство, либо имеет неправильное представление о нём. Текущий вопрос наталкивает прежде всего прочитать про систему наследования и свойство `__proto__`, а свойство `.prototype` можно обойти стороной. Оно есть, как-то там работает и хорошо. 

> Тут нюанс вот в чем. Ты будешь копать про прототипное наследование для вопроса Что такое прототип?, и как при этом не покопать про само свойство .protorype? Неужели никто не копает эту инфу? Да копают, конечно.

Боюсь, что не копают) ИМХО. Предлагаю:
* Что такое прототип? Какие возможности имеет/дает? **Рассказать про свойство `.prototype`.**

Или мне нравится вариант, предложенный @iatsdotfatr, добавить новый вопрос: 
* Рассказать про свойство prototype. Чем отличается это свойство у функции-конструктора от аналогичного у обычного объекта?

Таким образом, мы явно укажем, что надо изучить свойство `.prototype`, а если кто-то скажет, что свойство `.prototype` есть у каждого объекта, значит он плохо изучил тему и надо отправить перечитывать)

**Comment by mglknFSD** [comment]
Будет круто если ты закроешь этот вопрос. У меня не дошли руки. 🥇
