### ISSUE TITLE
Расписать более подробно про SOLID на первом мидле

### ISSUE THREAD

**Issue by clicktronix** [fullstack-development/developers-roadmap#35]

**Comment by Znack** [comment]
Пока план такой:
- Вынести SOLID из ООП, так как многие принципы не только к ООП относятся.
- Каждый принцип подробно описать вопросами, которые раскрывают не только смысл принципа, но и его цели и проблемы использования (например, когда не надо увлекаться DIP).
- Для всех принципов подробно в вопросах описать, как они связаны друг с другом и с остальными принципами (например, SRP vs Cohesion).
- Накидать подробно список источников.

**Comment by Znack** [comment]
@in19farkt @kinda-neat @Zarwlar @chmnkh @alextsk если у вас есть идеи крутых вопросов или источники, то welcome for contribution
