### ISSUE TITLE
Переработать JS вопросы

### ISSUE THREAD

**Issue by prodderman** [fullstack-development/developers-roadmap#368]
Предлагаю перенести блок вопросов про генераторы из мидла-1 на jun-3 JS, так как это по-сути базовая конструкция языка, не понятно, почему это считается мидловским знанием.

Так же на джуна-3 добавить блок вопросов про Proxy, так как в нашей практике все чаще приходится сталкиваться с этим

**Comment by FanManutd** [comment]
> Предлагаю перенести блок вопросов про генераторы из мидла-1 на jun-3 JS, так как это по-сути базовая конструкция языка, не понятно, почему это считается мидловским знанием.

Возможно, но у нас и так довольно объёмный JS на jun3. Можно конечно отдельной темой сделать. Лично я про генераторы знаю только из `redux-saga`. 

> Так же на джуна-3 добавить блок вопросов про Proxy, так как в нашей практике все чаще приходится сталкиваться с этим

Это точно тема для джуна? Что-то у нас слишком крутые джуны получаются) Мне допустим не приходилось непосредственно работать с Proxy. 

В общем, про перенос генераторов с mid1 на jun3 не уверен, нужно ещё мнения, желательно мидлов.
Добавить тему про Proxy можно, но на мидла.

**Comment by prodderman** [comment]
> Это точно тема для джуна? Что-то у нас слишком крутые джуны получаются) Мне допустим не приходилось непосредственно работать с Proxy.

думаю да, это тоже примитив языка, так как в нашей практике часто присутствует mobx, то базовое знание прокси не помешает, я думаю не нужно глубоко копать

> Возможно, но у нас и так довольно объёмный JS на jun3. Можно конечно отдельной темой сделать. Лично я про генераторы знаю только из redux-saga.

Возможно ты прав, генераторы редко используются, но так как это тоже примитив языка, я бы предложил базово с ним ознакомиться, возможно не так глубоко, как на мидле

**Comment by FanManutd** [comment]
Мне сильно смущает, что после добавления этих тем на jun3, он станет слишком раздутым. У нас и так не маленький jun3 по количеству вопросов и тем. Как альтернативу я бы предложил какие-то темы перенести с jun3 на jun2. Например гриды в CSS и промисы в JS. Тем самым освободив место на jun3. 

И я не уверен, что junior в привычном понимании обязан знать все примитивы языка. Всё таки генераторы и Proxy - это продвинутые темы, которые встречаются редко.

**Comment by prodderman** [comment]
Прокси и генераторы думаю не стоит глубоко изучать даже на мидле, достаточно базового понимания, так как в быту они редко используются, обычно на их основе написаны библиотеки (redux-saga или mobx). И понимать принцип работы этих примитивов достаточно, что бы не думать, что какой нибудь mobx работает магическим образом.

То что некоторые вопросы из третьего джуна можно перенести на второго, это я согласен.
