### ISSUE TITLE
[mid1/TypeScript] Убрать дублирующиеся вопросы и неактуальные вопросы, дополнить ресурсами

### ISSUE THREAD

**Issue by FanManutd** [fullstack-development/developers-roadmap#384]
> * Что такое структурная типизация? 
>   * Что такое номинативная типизация? Что такое Branding и Flavoring?
>   * Какие преимущества и недостатки у структурной и номинативной типизаций?

Убрать вопросы про структурную и номинативную типизацию. Эти вопросы есть на 2м джуне. Branding и Flavoring оставить.

> * Когда в TS проявляется Covariance? Когда Bivariance? Когда Contravariance?

Убрать часть вопроса про Bivariance. Насколько я понимаю, [вот](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#function-parameter-bivariance) единственный случай, когда в TS проявлялась бивариантность. Это поведение отключается с версии 2.6 флагом `strictFunctionTypes`. Флаг входит в правила `strict: true`, так что вопрос более не актуален. Убрать связанные с ним ресурсы

> * Что такое Type Widening? Как этот механизм влияет на type safety в TS?

Добавить [ресурс](https://github.com/microsoft/TypeScript/wiki/Reference-Checker-Widening-Narrowing) и [ресурс](https://www.executeprogram.com/courses/everyday-typescript/lessons/type-widening).

> * Что такое Refinement? Как он работает в контексте Discriminated Unions?

`Refinement` теперь в документации называется `Narrowing` и все вопросы касающиеся `Narrowing`, в том числе `Discriminated Unions` есть на 2м джуне. 

> * Что такое вывод типов (относительно любого языка)? В каких случаях TS может выводить типы для генериков? В каких случаях TS автоматически выводит переменную типа как any?

Во первых 2й вопрос, про вывод типов для дженериков уже есть на 2м джуне. Во 2х все эти вопросы можно перенести на 2го джуна.

**Comment by Geksanit** [comment]
Я бы оставил вопосы про структурную и номинативную типизацию, это всё равно придется вспомнить и рассказать при обсуждении branding/flaworing
