### ISSUE TITLE
Перенести старшего джуниора

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#4]
Как я указал в #3 наш текущий уровень старшего джуна будет распилен на два. Здесь останется только продвинутый материал, плюс будем думать над его расширением. 

Из текущей версии сюда перенести:
- Изучить книгу Макконнелла "Совершенный код" 
- Изучить книгу (можно только саммари с smartreading.ru) "Принцип пирамиды Минто"
- JS
  - Регулярки
  - Promises
- Системы сборок
- Безопасность
- Advanced Git
- API

**Comment by Znack** [comment]
Предлагаю сюда добавить новые темы по advanced HTML, advanced CSS и advanced JS, которые у нас ещё не покрыты в текущих уровнях. Про JS, насколько я помню, у нас слабовато покрыт новый стандарт, разные тонкости в областях видимости в аргументах функции (где можно творить лютую дичь теперь), про то, как десахарятся классы в  ES6.

**Comment by Znack** [comment]
Точно сюда в JS надо пернеести вопросы с младшего мидла про работу с данными: 
- Что такое Symbol? Какие примеры использования есть?
- В чем отличия между массивами и объектами подобными массивам?
- Привести примеры объектов, подобных массивам
- Деструктуризация
- Утечки памяти

**Comment by Znack** [comment]
Итераторы и Генераторы пока предлагаю не переносить, наверное. Хотя тут не уверен, кто что думает?

**Comment by Znack** [comment]
Сюда же добавить и проработать TypeScript и React

**Comment by clicktronix** [comment]
Мне кажется жирноватый старший джун получится, совсем не пропорциональный предыдущему уроввню. Может гит не будем бить на 2 уровня? Еще предлагаю добавить вопросы по работе с DOM

**Comment by Znack** [comment]
ну тут на самом деле не очень много, мы просто ещё обычного джуна прокачаем :)

Мне сейчас наоборот тут кажется тонким уровнем, все основное в обычном джуне осталось, тут только Макконнелл, сложный GIT и всё, остальное там быстро и просто довольно

**Comment by Znack** [comment]
Про DOM согласен кстати, надо его причем побить и на этого джуна и на обычного (#3)

**Comment by krashaen** [comment]
я предлагаю не дробить гит на два, а перенести его в среднего джуна

**Comment by krashaen** [comment]
а webpack куда уходит?

**Comment by Znack** [comment]
> я предлагаю не дробить гит на два

почему? я это сделал для того, чтобы уже на второй уровне про гит что-то знали, но чтобы уровень не стал слишком сложным.

**Comment by Znack** [comment]
> а webpack куда уходит?

а, забыл, это на текущий уровень, на старшего джуна :)

**Comment by krashaen** [comment]
> почему? я это сделал для того, чтобы уже на второй уровне про гит что-то знали, но чтобы уровень не стал слишком сложным.

 Я не вижу смысла гит бить на два, это ж не js там прям супер сложных вещей нет, ну как по мне разом изучить тему и все чем изучать кусками. @chmnkh @Zarwlar как думаете?

**Comment by chmnkh** [comment]
Я завтра буду смотреть прям подробно, но в теории, я бы добавил в гит чуть-чуть вопросов еще, типа черрипика, стэша, еще может что-нибудь. Тогда он станет жирноватым возможно, и мб будет смысл разделить. В том виде как сейчас гит делить особо смысла нету как мне кажется, согласен.

**Comment by Znack** [comment]
Ну давайте здесь всё про внутреннее устройство и про продвинутые темы оставим, это необязательно знать на обычном джуне, я думаю
