### ISSUE TITLE
Добавить вопросы по книге "Объектно-ориентированное мышление" Мэтта Вайсфельда в 1 мидла

### ISSUE THREAD

**Issue by clicktronix** [fullstack-development/developers-roadmap#43]

**Comment by Znack** [comment]
@chmnkh @kinda-neat Я так понимаю, было решено отказаться от этой книги в итоге?

**Comment by chmnkh** [comment]
мои ощущения такие: книга сильно поверхностная, похожа на какую-то методичку, после ее прочтения у меня ничего не прибавилось вообще

после нее я прочитал первые сколько-то глав Буча, и мне зашло сильно лучше, поэтому я за то, чтобы выпилить эту книгу и рассмотреть вариант добавления первых разделов Буча

еще точно читали Леха Андреич, Ваня, @GoodDayTodayOkey, @Zarwlar, насколько они именно за то, чтобы выпилить, я не могу сказать, надо явно задать вопрос

**Comment by Zarwlar** [comment]
Я думаю, её не стоит делать обязательной, мне кажется, что её нужно просто оставить в источниках.

В книге рассматриваются базовые вещи, без глубины, и на сколько я знаю @Znack как раз что-то вроде такого и хотел. Т.е. можно было бы оставить её, если бы тема ООП сдавалась только по ней, но скорее всего, будет происходить так, что люди просто дважды будут отвечать на одни и те же вопросы: сперва на вышестоящие вопросы в топике по ООП, а потом на вопросы из книги. Я более чем уверен, что вопросы будут повторяться (хотя, когда я добавлял МР с вопросами из этой книги, я старался сделать так, чтобы вопросы не повторялись с уже имеющимися)

Вообще, я бы сравнил эту книгу с learn haskell for great good только для ООП и на порядок хуже по качеству содержащейся информации))

**Comment by kinda-neat** [comment]
Я не читал, но против, достаточно отзывов чтобы не читать. Уж лучше написать какую-нибудь приложуху, либо попроектировать на словах/в виде UML, контрактами

**Comment by alextsk** [comment]
я за то чтобы описать сами вопросы и дать варианты где искать на них ответы, кому то может и вайсфилд подойдет. а пересказывать книгу смысла я не вижу, это не макконелл

**Comment by GoodDayTodayOkey** [comment]
Я поддерживаю мнение @alexskt можно составить список базовых вопросов, а книгу оставить как один из источников по ООП.

**Comment by kinda-neat** [comment]
Вопросы уже есть, осталось только эту книгу в источники положить (хотя я против, хочется только жирные в плане пользы источники держать в идеале) и закрыть это ишью

**Comment by chmnkh** [comment]
Ну кстати плюсану Макс.

Мне, например, жалко времени, потраченного на эту книгу. При этом, я всегда стараюсь все приведенные источники читать, и даже если бы эта книга просто висела в источниках, я бы ее прочел, так же жалел, и ныл потом, что почему она у нас в источниках лежит))

На самом деле если так задуматься, то чем отличается наличие книги в источниках и в списке вопросов, помимо того, что если она в списке вопросов, то по ней явно разговаривают? Имхо - список источников, если ты хочешь нормально подготовиться, обязателен к изучению, пусть это и на совести каждого и формально не проверяется.

Т.е. таким образом, убирание книги в список источников проблему того, что приходится время тратить не шибко полезно не решает, ящитаю.

**Comment by chmnkh** [comment]
Тут просто надо задать вопрос явно, была ли эта книга полезной для вас или нет? @GoodDayTodayOkey @Zarwlar @alextsk

**Comment by Zarwlar** [comment]
Ну какая-то польза точно была, но ей не стоит быть в чеклисте, мне кажется

**Comment by hersveit** [comment]
Согласен с тем, что в книге описываются основы и достаточно поверхностно. Но все же если ты до этого читал только статьи в нете как-то структурировать знания все равно надо. Может не эту книгу, но Буча я еще не читал

**Comment by Znack** [comment]
Все, убираю тогда книгу: https://github.com/fullstack-development/developers-roadmap/pull/97
