### ISSUE TITLE
Добавить вопросы про продвинутые вещи в HTML

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#5]

**Comment by krashaen** [comment]
Я бы добавил эти вот вопросы:
1. Работа с сеткой. Я думаю полезно будет сделать пару каких то сеток, типа лист плиток, который может сужаться расширяться. Может просто разметить хедер, футер, меню, закрепить футер внизу. Попросить реализовать это разными способами(гриды, флексы и тд). Тут как бы да, вроде все знания есть, но они только в теории, а тут прям потыкаться надо будет.

1. Добавить вопрос, как верстать письма.  Да, согласен очень редкий кейс, но общее представление на мой взгляд должно быть https://habr.com/ru/post/252279/

1. Может стоит добавить знание фреймворков, бутстрап Foundation, материал

1. Как использовать/писать полифилы

**Comment by GoodDayTodayOkey** [comment]
1, 2, 3 -  за, а вот насчет полифилов, есть куча npm пакетов, не вижу в этом особой нужды.

**Comment by NikitaRzm** [comment]
Полагаю, основная проблема с полифиллами в том - что их куча. Хорошо было бы в них ориентироваться, среди полифиллов все +- стабильно, т.к. это вещи вечные, потому если полифиллы делать - то скорее как рекомендацию к тому, какие полифиллы для чего рекомендуется.

**Comment by GoodDayTodayOkey** [comment]
А еще вопрос про фреймворки, у нас применяются на проектах вот эти ребята бутстрап Foundation? Если пока нет, то планируется ли это делать?

**Comment by Znack** [comment]
> А еще вопрос про фреймворки, у нас применяются на проектах вот эти ребята бутстрап Foundation? Если пока нет, то планируется ли это делать?

По-моему нет, можно добавить в темы

**Comment by chmnkh** [comment]
> 1. Работа с сеткой. Я думаю полезно будет сделать пару каких то сеток, типа лист плиток, который может сужаться расширяться. Может просто разметить хедер, футер, меню, закрепить футер внизу. Попросить реализовать это разными способами(гриды, флексы и тд). Тут как бы да, вроде все знания есть, но они только в теории, а тут прям потыкаться надо будет.

построить ту или иную сетку - сильно частная задача, мне кажется, чтобы это прямо спрашивать
можно добавить, конечно, в качестве практики что-то подобное рядом с соответствующими темами (флексы там, гриды), но опять же это либо сильно просто (тогда это будет тупо трата времени собеседования), либо какая-то сильно частная задача, не понять нафиг нужная

> 2. Добавить вопрос, как верстать письма.  Да, согласен очень редкий кейс, но общее представление на мой взгляд должно быть https://habr.com/ru/post/252279/

мне кажется вопросы из области "очень редкий кейс" не должны попадать в топики знаний в принципе)

> 3. Может стоит добавить знание фреймворков, бутстрап Foundation, материал

тут вроде в соседних ишью на эту темы высказались все, кто хотел

> 4. Как использовать/писать полифилы

в использовании полифилов есть какие-то прямо особенности, про которые стоит спрашивать?
"писать полифил" - это как раз на мой взгляд редкий кейс, про "редкие кейсы" в целом я высказался выше

**Comment by krashaen** [comment]
@chmnkh Позиция понятна) А есть идеи, что можно добавить?)

**Comment by krashaen** [comment]
@Znack думаю можно этот раздел закрывать)
