### ISSUE TITLE
Добавить вопросы про продвинутые вещи в CSS

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#6]

**Comment by krashaen** [comment]
Интересная тема на мой взгляд
1. Ретиновая графика https://habr.com/ru/post/150071/

**Comment by krashaen** [comment]
Может стоит добавить гриды? кто согласен ставьте на на этот коммент палец вверх)

**Comment by GoodDayTodayOkey** [comment]
Насчет ретиновая графика, у меня сомнения, поскольку уже есть блок посвященный svg на собесе при поступлении.

**Comment by krashaen** [comment]
> Насчет ретиновая графика, у меня сомнения, поскольку уже есть блок посвященный svg на собесе при поступлении.

Немного тут не понял, тут речь идет о понимании как устроены ретина дисплеи и какие это подводные камни за собой несет, а svg в данном случае идет как один из вариантов решения этой проблемы

**Comment by GoodDayTodayOkey** [comment]
> > Насчет ретиновая графика, у меня сомнения, поскольку уже есть блок посвященный svg на собесе при поступлении.
> 
> Немного тут не понял, тут речь идет о понимании как устроены ретина дисплеи и какие это подводные камни за собой несет, а svg в данном случае идет как один из вариантов решения этой проблемы

На мой взгляд не стоит привязываться к типу дисплеев, и рассматривать под них отдельные варианты адаптации изображений. Сегодня это ретина, завтра придумают что то новое. Мне кажется это статья больше подошла бы в пункт svg как пояснение почему не стоит использовать растровые изображения.

**Comment by NikitaRzm** [comment]
DPI, Pixel-rate - тема тоже в принципе на года. Это можно просто изучать вне контекста ретины и high-res дисплеев, но на данный момент хорошим экземпляром high-res является ретина :)

**Comment by krashaen** [comment]
> На мой взгляд не стоит привязываться к типу дисплеев, и рассматривать под них отдельные варианты адаптации изображений. Сегодня это ретина, завтра придумают что то новое. Мне кажется это статья больше подошла бы в пункт svg как пояснение почему не стоит использовать растровые изображения.

На самом деле это статья только пояснение о том что я имел в виду, а так это ж целый раздел. Тут нужны еще мнения похоже)

**Comment by in19farkt** [comment]
> На мой взгляд не стоит привязываться к типу дисплеев, и рассматривать под них отдельные варианты адаптации изображений. Сегодня это ретина, завтра придумают что то новое. Мне кажется это статья больше подошла бы в пункт svg как пояснение почему не стоит использовать растровые изображения.

Что значит "не стоит использовать растровые изображения"? svg не может покрывать все 100% случаев. Например ты верстаешь страницу команды, как ты фотографии членов команды будешь с помощью svg отображать?

**Comment by krashaen** [comment]
Тоже интересная тема, переменные в css https://frontender.info/css-variables-why-should-you-care/

**Comment by GoodDayTodayOkey** [comment]
> > На мой взгляд не стоит привязываться к типу дисплеев, и рассматривать под них отдельные варианты адаптации изображений. Сегодня это ретина, завтра придумают что то новое. Мне кажется это статья больше подошла бы в пункт svg как пояснение почему не стоит использовать растровые изображения.
> 
> Что значит "не стоит использовать растровые изображения"? svg не может покрывать все 100% случаев. Например ты верстаешь страницу команды, как ты фотографии членов команды будешь с помощью svg отображать?

adobe illustratorом

**Comment by krashaen** [comment]
1. В чем разница между `id` и `class`?
1. Рассказать подробно о префиксах:
    * `-moz-*`;
    * `-ms-*`;
    * `-webkit-*`;
    *  `-o-*`;
    * `-khtml-*`.
1. Вопросы по картинкам:
    * Когда стоит использовать тег `img` а когда `background-image`
    * Что такое `progressive jpeg`? 
1. Как работает `calc()`?
1. Как работают треугольники CSS? Не частый конечно кейс, но я пару раз делал треугольники. [Вот это имею в виду)](http://qaru.site/questions/707/how-do-css-triangles-work)
1. Какие символы действительны в именах/селекторах классов CSS?
1. Как работает `@import`?

У нас кстати нигде нет вопроса про `cursor` но он вроде очевиден.

**Comment by chmnkh** [comment]
> 1. В чем разница между `id` и `class`?
> 2. Рассказать подробно о префиксах:
>    
>    * `-moz-*`;
>    * `-ms-*`;
>    * `-webkit-*`;
>    * `-o-*`;
>    * `-khtml-*`.
> 3. Вопросы по картинкам:
>    
>    * Когда стоит использовать тег `img` а когда `background-image`
>    * Что такое `progressive jpeg`?
> 4. Как работает `calc()`?
> 5. Как работают треугольники CSS? Не частый конечно кейс, но я пару раз делал треугольники. [Вот это имею в виду)](http://qaru.site/questions/707/how-do-css-triangles-work)
> 6. Какие символы действительны в именах/селекторах классов CSS?
> 7. Как работает `@import`?
> 
> У нас кстати нигде нет вопроса про `cursor` но он вроде очевиден.

1. Странный вопрос, очевидный вроде как.
2. Есть вопрос про автопрефиксер, который это покрывает. 
3. Про имг нормас, про джпег надо поресерчить
4. Что в ответе должно быть?
5. Не вижу смысла, есть куча генераторов для треугольников, никто же их не будет руками писать.
6. зочем?
7. Что в ответе должно быть?

**Comment by krashaen** [comment]
> 4. Что в ответе должно быть?

Тут я хотел бы услышать что такое, как считает, какие параметры принимает, в каких единицах можно задавать, какие операции допустимы

> 7. Что в ответе должно быть?

я тут коряво наверное сформулировал, лучше типа того: почему в Html подключать стили  через `link` а не через `@import`? [вот об этом речь](https://habr.com/ru/post/57012/)

**Comment by chmnkh** [comment]
ну `calc` в принципе можно мб

про импорт я не уверен, мы же руками не вставляем стили на страницу

**Comment by clicktronix** [comment]
@krashaen 1, 2 думаю на продвинутые темы не особо тянут. 3 норм. 4 надо как то переформулировать и более конкретно просить про кейсы. 5 думаю, редкий кейс чтоб его спрашивать(сам до сих пор треугольники не рисовал). 6 не понял вопрос. 7 расширить вопрос, как то конкретней спросить, тоже не понял что требуется в ответе

**Comment by Znack** [comment]
Про треугольники кстати норм вопрос, только я бы сформулировал "как сделать треугольник на чистом css?". И это надо @krashaen тебе тоже отдельно погуглить, какие статьи вылазят на эту тему и какие ещё способы есть :)

**Comment by GoodDayTodayOkey** [comment]
1. не уверен что заслуживает быть вопросом 2. точно нет, уже есть вопрос про автопрефиксер 3. согласен ток с первой половинкой, нашел статью http://xiper.net/learn/tegofenshuj/img-vs-backround-image возможно подойдет как для указания источника, про прогрессивный jpeg - это больше  дизайнерский вопрос 4. Встречается на практике, поэтому думаю стоит знать его синтаксис 5. Про треугольники думаю можно вынести в практическое задание. 6. Нет. 7. Не актуально, мы же руками не вставляем стили на страницу (с) chmnkh

**Comment by Znack** [comment]
> прогрессивный jpeg

Это чисто фронтендерский вопрос :) Дизайнеры тут не всегда заморачиваются, да и не должны.

**Comment by krashaen** [comment]
@Znack думаю можно этот раздел закрывать)

**Comment by Znack** [comment]
@krashaen а почему закрывать? Вроде же нашли темы, которыми можно расширить?

**Comment by krashaen** [comment]
> @krashaen а почему закрывать? Вроде же нашли темы, которыми можно расширить?

@Znack Все что тут одобрили, было добавлено в отдельном ишью. Больше идей не было, поэтому мне кажется неактуальным больше этот раздел)
