### ISSUE TITLE
 Добавить redux на jun-2

### ISSUE THREAD

**Issue by krashaen** [fullstack-development/developers-roadmap#61]

**Comment by chmnkh** [comment]
2 пробела перед "на", емае!

**Comment by krashaen** [comment]
> 2 пробела перед "на", емае!

пофикшено 👌

**Comment by krashaen** [comment]
@in19farkt @Znack @chmnkh @kinda-neat Тут предлагаю похоливарить по поводу необходимости внедрения в карту редакса. Что думаете?

**Comment by in19farkt** [comment]
Конкретно про редакс, ну хз. Мне кажется я в один абзац смогу уместить основную концепцию и принцип работы :)

Возможно нужно проработать вопросы по стейт менеджменту и в контексте этих вопросов обсудить существующие на данный момент инструменты, тогда картина будет более полной и человек поймет почему мы работаем именно с редаксом, а не с mobx, например, какие есть преимущества и недостатки у разных подходов.

**Comment by chmnkh** [comment]
> Возможно нужно проработать вопросы по стейт менеджменту и в контексте этих вопросов обсудить существующие на данный момент инструменты, тогда картина будет более полной и человек поймет какие есть преимущества и недостатки у разных подходов, почему мы работаем именно с редаксом, а не с mobx.

это не к джунам уж точно

в целом редакс может быть и не стоит на джунов добавлять

возможно стоит подумать в сторону реакт/редакс специфических штук всяких, например чуваки часто фейлятся с тем, как работает `connect`, возвращают в селекторах всякие новые объекты, в креэйт селекторе пишут селекторы, которые возвращают стейт, всякие такие штуки возможно стоит покрыть небольшом количеством вопросов, но это не точно

**Comment by Znack** [comment]
Чисто с практической точки зрения, редакс в уровнях поможет побороть то, что у нас иногда реально джуны уже больше полугода работают, а все равно с трудом понимают, что такое `connect`, как пользоваться селекторами и тд. Но я не уверен, что эту проблему надо именно уровнями решать, а то у нас опять раздуется карта слишком специфичной штукой, которая не так критична, пожалуй. Может быть, вернуться к этому вопросу после того, как на мидлах в целом вопросы state-management-а проработать?

**Comment by kinda-neat** [comment]
Короч я тоже не знаю, с одной стороны это nice-to-have (там куча о чем можно поговорить, зачем селекторы/actionCreators, идиоматичный редакс, нормализация стейта, конская дока + кучу материалов чуваки написали в контексте редакса, etc., но это с точки зрения "интересно поговорить", но тратить это время собеса не очень, дорого), с другой must-have (мы используем в работе и чтобы делать работу эффективно надо понимать как оно все работает и почему так)

**Comment by kinda-neat** [comment]
вообще я против и хотел бы чтобы про это реально читали сами, иначе как можно делать работу эффективной если ты не шаришь за инструменты которые используешь? С одной стороны непонимание, с другой стороны я реально вижу как у большинства с этим in-depth сложно/никак

**Comment by kinda-neat** [comment]
а еще я в последнее время думаю по поводу раздувания уровней и поддержу Леху, хотелось бы иметь must-have вещи в вопросах, чтобы тратить время максимально на пользу, а не на то чтобы обговорить то что изи гуглится/понимается/узкая тема

**Comment by krashaen** [comment]
> а еще я в последнее время думаю по поводу раздувания уровней и поддержу Леху, хотелось бы иметь must-have вещи в вопросах, чтобы тратить время максимально на пользу, а не на то чтобы обговорить то что изи гуглится/понимается/узкая тема

у меня тоже двоякие чувства, вроде бы и каждый день используется, но вроде бы и можно самому прочесть. Возможно этот раздел и нужен, но не в виде вопросов по разделам доки мне кажется. Тогда наверное соглашусь с Серегой:

>  Может быть, вернуться к этому вопросу после того, как на мидлах в целом вопросы state-management-а проработать?

Пока оставим вопрос открытым)

**Comment by kinda-neat** [comment]
Я думаю стопудово надо добавить рекомендуемые источники по react, redux, react-redux, не знаю куда положить, но сделать это надо, чтобы чувак когда к нам приходил сразу брался за изучение с указанных источников, по react - это обязательно прочитать всю доку, по redux по-хорошему тоже всю доку, но хорошо было бы как минимум https://redux.js.org/faq основательно прошерстить, там куча вопросов и ответов наперед, что увеличит вероятность что будут шипить более качественный код
