### ISSUE TITLE
Отрефакторить топики по стандартам оформления 

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/developers-roadmap#68]
https://github.com/fullstack-development/developers-roadmap/pull/60

**Comment by krashaen** [comment]
Нужно пройти по всем файлам из уровней и проверить на соответствие оформления всех  правил, которые составлены и лежат [тут](https://github.com/fullstack-development/developers-roadmap/blob/master/requirements.md#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2)

**Comment by krashaen** [comment]
@Frolikow ты получается все уровни переработал? можно закрывать?

**Comment by Frolikow** [comment]
> @Frolikow ты получается все уровни переработал? можно закрывать?

Все, по фронту )
