### ISSUE TITLE
Добавить вопросы про TypeScript для 2 и 3 джунов

### ISSUE THREAD

**Issue by Znack** [fullstack-development/developers-roadmap#8]
Здесь будет две части, одна в обычного джуна, другая про продвинутые вещи в старшего. Затем отдельным пунктом в разные уровни мидлов добавим теорию, которая за системами типов стоит

**Comment by GoodDayTodayOkey** [comment]
Я бы предложил все что здесь  https://www.typescriptlang.org/docs/handbook/basic-types.html выше Advanced Types на обычного джуна вынести, а остальное в старшего. В вопросах оставить только что относится к юс кейсам которые применяются на практике.

**Comment by in19farkt** [comment]
Еще есть косяк - не все фичи описаны в разделе `handbook`, многое я нахожу только в разделе `what's new`... Например, последняя фича `as const`

**Comment by Znack** [comment]
@in19farkt а можешь выписать список таких фичей сюда?

**Comment by Znack** [comment]
@GoodDayTodayOkey согласен, примерно так и ожидал :)

**Comment by in19farkt** [comment]
@Znack на вскидку не скажу. По хорошему нужно перечитывать всё что есть на typescriptlang, чтобы составить такой список)) Я могу конечно этим заняться, но хз сколько это займет у меня времени.

И еще некоторые фичи в разделе `what's new` более глубоко разобраны.

**Comment by Znack** [comment]
Ну если у тебя будет время на неделе, то было бы круто такой списочек составить :)

**Comment by in19farkt** [comment]
Я пока ишу создам, если смогу за нее взяться, то заасайню на себя когда начну.

**Comment by GoodDayTodayOkey** [comment]
Для обсуждения вопросов по typescript к джуну-2:

    1. Дополнительные базовые типы в typescript. Каково предназначение и способы задания?
    2. Каким способом можно указать более конкретный тип сущности в typescript, относительно его текущего? Какие имеются ограничения и недостатки такого подхода?
    3. Каким способом можно создать массив доступный только для чтения?
    4. Способы задания массива для типов?
    5. Для чего предназначены интерфейсы? 
    6. Каким способом можно задать свойство опционально? 
    7. Каким способом можно задать интерфейс функции и обеспечить правильность проверки типов? 
    8. Каким способом можно задать свойство доступное только для чтения? 
    9. Каким способом можно создать индексируемый тип и какие это несет ограничения?
    10. От чего могут расширяться интерфейсы? Какие накладывает ограничения расширение от класса? 
    11. Каким способом можно задать интерфейс для класса?  
    12. Модификаторы свойств классов, их назначения.
    13. Каким способом можно затипизировать статические свойства класса? 
    14. Абстрактные классы в чем отличие от интерфейсов?
    15. Можно ли затипизировать this фунуции?
    16. Каким способом можно реализовать перегрузку функции?
    17.  Для чего нужны generics?
    18.  Каким образом можно добаваить в generics тип дополнительное свойство? Что делать если необходимо использовать  ключи generics типа? 

Вопросы к старшем

**Comment by NikitaRzm** [comment]
@GoodDayTodayOkey у меня непонимание увы почти по каждому вопросу по TS, можешь вкратце отдельным комментом описать, что нужно рассказать на вопрос или просто детальнее его раскрыть?)

Я затрудняюсь просто вот на такие вопросы ответить: `как обеспечить правильность проверки типов` - потому что тогда надо вводить какую-то проблему неправильности.

Ну и подобные вопросы у меня почти по каждому есть, нужно пояснить отдельно, и мы пожалуй поможем переформулировать.

**Comment by GoodDayTodayOkey** [comment]
Принято,  добавлю вместе с вопросами на джун-3) Если имеется сейчас желание посмотреть то вопросы были взяты с https://www.typescriptlang.org/docs/handbook/basic-types.html первые 6 тем в handbook.

**Comment by GoodDayTodayOkey** [comment]
Описание ответов на вопросы:
       джун-2:
    1. Типы отсутвующие в js: Array (number[], Array<number>),  Tuple( let x: [string, number];) Типы кортежей позволяют вам выражать массив, в котором тип фиксированного числа элементов известен, но не обязательно должен быть одинаковым., Enum (enum Color {Red = 1, Green, Blue}) enum - это способ дать более понятные имена наборам числовых значений.,  Any, Void,  Never, 
    2. В TypeScript интерфейсы играют роль именования типов и являются мощным способом определения контрактов в вашем коде, а также контрактов с кодом вне вашего проекта.
    3. interface SquareConfig { color?: string; width?: number; } 
    4. interface SearchFunc { (source: string, subString: string): boolean; }
       Чтобы типы функций правильно проверяли тип, имена параметров не должны совпадать. let mySearch: SearchFunc; mySearch = function(src: string, sub: string): boolean { let result = src.search(sub); return result > -1; }
    5. interface ReadonlyStringArray { readonly kobra: string; }
    6. interface Shape { color: string; } interface PenStroke { penWidth: number; } interface Square extends Shape, PenStroke { sideLength: number; } либо class Control { private state: any; } interface SelectableControl extends Control { select(): void; } Когда тип интерфейса расширяет тип класса, он наследует членов класса, но не их реализации. Интерфейсы наследуют даже приватные и защищенные члены базового класса. Это означает, что когда вы создаете интерфейс, который расширяет класс закрытыми или защищенными членами, этот тип интерфейса может быть реализован только этим классом или его подклассом.
    7. class Button implements SelectableControl { select() { } }
    8. public, private, static, protected, readonly.
    9. interface ClockConstructor {k: number; new(): void;} const Clock: ClockConstructor = class Clock {static k = 5;}
    10. Отличие от интерфейса, абстрактный класс может содержать детали реализации для своих членов. Ключевое слово abstract используется для определения абстрактных классов, а также абстрактных методов в абстрактном классе. 
       abstract class Animal { abstract makeSound(): void; move(): void { console.log("roaming the earth..."); } }
    11. function multiply(operand: number): this { this.value *= operand; return this; }
    12. function pickCard(x: {suit: string; card: number; }[]): number;                                     function pickCard(x: number): {suit: string; card: number; };                                       function pickCard(x): any { if (typeof x == "object") { let pickedCard = Math.floor(Math.random() * x.length); return pickedCard; }                                                          if (typeof x == "number") { let pickedSuit = Math.floor(x / 13); return { suit: suits[pickedSuit], card: x % 13 }; } }
    13.  Для предоставления способ захвата типа аргумента функции таким образом, чтобы можно было использовать его для обозначения того, что возвращается.
       function identity<T>(arg: T): T { return arg; }
    14.  interface Lengthwise { length: number; }; 
       function loggingIdentity<T extends Lengthwise>(arg: T): T { console.log(arg.length);  }
       function getProperty<T, K extends keyof T>(obj: T, key: K) { return obj[key]; }

**Comment by in19farkt** [comment]
Блин, зачем моноспейсом-то? читать же невозможно((

**Comment by NikitaRzm** [comment]
@GoodDayTodayOkey оформи пожалуйста многострочный код мультилайн-выделением кода через тройные кавычки, я отредактировал твой окммент для примера, на все меня не хватает редактировать ))

**Comment by krashaen** [comment]
Ага, еще тип javascript дай чтоб подсветка была) типа так 
` ```javascript
код
` ```

**Comment by Znack** [comment]
Сделали и вмёржили ПРы
