### ISSUE TITLE
Рефакторинг реакт вопросов на 2 джуна

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/developers-roadmap#86]
1. Термин "виртуал дом" надо выпилить, как-то переиначить вопрос
2. Вопрос про `null`, `void 0`, `boolean` значения по факту 2 раза написан, надо удалить один из них

**Comment by Znack** [comment]
Да ты можешь сразу ПР открывать и исправлениями, тут через веб это делать на гитхабе почти также просто, как ишью заводить :)

**Comment by chmnkh** [comment]
да я чтобы не забыть самому это открыл)
