### ISSUE TITLE
Обсуждение: добавить вопросы mid1 -> Redux-saga, mid2 -> Redux-observable

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [fullstack-development/developers-roadmap#96]
Как думаете стоит добавлять?

**Comment by Znack** [comment]
Redux-observable только если отдельным ишью и после того, как реактивное прогграммирование будет хорошо проработано и сдано хотя бы парой человек :)

Саги с другой стороны можно, да. Но я бы основы на джуна запихал вообще, все равно это джуну уже нужно знать

**Comment by GoodDayTodayOkey** [comment]
Понял, хорошо, я тогда создам пр на джуна.

**Comment by GoodDayTodayOkey** [comment]
@NikitaRzm Тут как раз и вскрываются две проблемы 1) работник нужен для работы, и то что он знает о стэйт-менеджменте и сайд-эффектах !== что он будет правильно использовать инструмент разработки, хотя бы по то причине, что он не знает всех его возможностей, и пишет свои костыли. А все потому что он слышал о либе, знает о ее приемуществах относительно других аналогов, но не разобрался с ней до конца, хотя она и входит в стэк компании.  2) будем реалистами, я не помню еще таким образом пришедших в компанию джунов. P.S. даже поверхностное изучение hh говорит о том что работодатели очень прагматичны в плане используемых стеков технологий.

**Comment by NikitaRzm** [comment]
> @NikitaRzm Тут как раз и вскрываются две проблемы 1) работник нужен для работы, и то что он знает о стэйт-менеджменте и сайд-эффектах !== что он будет правильно использовать инструмент разработки, хотя бы по той причине, что он не знает всех возможностей либы, и пишет свои костыли. А все потому что он слышал о либе, знает о ее приемуществах относительно других аналогов, но не разобрался с ней до конца, хотя она и входит в стэк компании. 2) будем реалистами, я не помню еще таким образом пришедших в компанию джунов. P.S. даже поверхностное изучение hh говорит о том что работодатели очень прагматичны в плане используемых стеков технологий.

Мне вижн понятен. Использование по документации != эффективное использование библиотеки.

Но эффективное использование (паттерны хороших приемов саги например, этакий cookbook) - все же не достоин все еще внесения в карту компетенций к нам. Можно оформлять это отдельным документом, который давать на чтение например. Это повысит эффективность работы в стеке, раскроет то, чего может не быть в доке. Но компетенцию инженера это особо не повышает и в карте развития, я считаю, этому не место.

P.S. Анализ рынка по HH нерепрезентативен, я имел ввиду людей, которые ходят на собеседования (мои товарищи), которые устраиваются с горизонтальным переходом между технологиями без особых проблем со стороны работодателя, ну и по своему личному опыту собеседований.

**Comment by Znack** [comment]
В общем подведём итог:

- Поинты за то, чтобы добавлять вопросы по сагам:
  - Используем в непосредственной разработке.
  - Без знания саг разработчик будет костылять.
  - Там есть крутые концептуальные вещи, которые стоило бы знать.
- Поинты за то, чтобы не добавлять:
  - В разработке используется далеко не везде и не всегда (не будем в публичном топике перечислять проекты).
  - Проблема незнания саг решается чтение доки и обсуждениями в рамках код-ревью, выносить это на обсуждение уровней не замена этому
  - Концептуальные вещи лучше оставить абстрактными и они уже есть на мидле, там же можно сагу просто как пример рассмотреть, и то по желанию собеседующих.
  - Уровни и так довольно раздутые, плюс к конкретным решениям привязываться — уменьшать гибкость и усложнять прохождение уровней.
  -  Зная фундаментальные вещи, сага быстро изучается и понимается. Плюс к тому же у разработчика выбор именно саги будет обусловлен не тем, что он тупо уже читал их доку, а потому что он понимает, как именно и какие именно задачи он будет решать с помощью саг.

Плюс добавлю от себя ещё пункт:
  - В принципе, пару вопросов можно добавить на мидловские уровни по уже имеющимся темам в формате "как саги помогают решить эту проблему?". Причем вроде это уже в одном месте на ФП у нас либо было (про управление сайд эффектами), либо ещё есть. Возможно, потом еще похожий вопрос появится в теме про такой подход в проектировании, как представление проблемы в виде first class citizen (тут саги таким образом представляют сайд-эффекты). Но это в будущем и лучше этот вопрос рассмотреть отдельно.

Итог: пока ишью закрываю, если у кого-то есть ещё аргументы, то не стесняйтесь ниже писать :)
